import Link from 'next/link'

type Action = { href: string; label: string; variant?: 'primary' | 'secondary' }
type Section = {
  title: string
  description: string
  actions: Action[]
}

const SECTIONS: Section[] = [
  {
    title: 'Alerts',
    description: 'Draft, approve, and publish alerts. Review Scout-generated drafts and edit existing entries.',
    actions: [
      { href: '/admin/alerts', label: 'Manage Alerts', variant: 'primary' },
      { href: '/admin/alerts/new', label: 'New Alert', variant: 'secondary' },
    ],
  },
  {
    title: 'Sources',
    description: 'Intelligence sources scraped by Claude Scout. Control tiers, frequency, and Firecrawl usage.',
    actions: [
      { href: '/admin/sources', label: 'Manage Sources', variant: 'primary' },
      { href: '/admin/sources/new', label: 'New Source', variant: 'secondary' },
    ],
  },
  {
    title: 'Intel',
    description: 'Raw findings from Claude Scout. Filter by confidence, source, and status; reject noise.',
    actions: [
      { href: '/admin/intel', label: 'View Intel', variant: 'primary' },
    ],
  },
  {
    title: 'Programs',
    description: 'Loyalty programs (airlines, hotels, cards, portals) that alerts can be tagged against.',
    actions: [
      { href: '/admin/programs', label: 'Manage Programs', variant: 'primary' },
    ],
  },
  {
    title: 'Content Pipeline',
    description: 'Long-form content ideas generated by the Writer agent during the daily brief.',
    actions: [
      { href: '/admin/content-ideas', label: 'Content Ideas', variant: 'primary' },
    ],
  },
  {
    title: 'Subscribers',
    description: 'Newsletter subscribers. Review active/inactive counts and deactivate individual addresses.',
    actions: [
      { href: '/admin/subscribers', label: 'Manage Subscribers', variant: 'primary' },
    ],
  },
  {
    title: 'Daily Briefs',
    description: 'Preview past daily briefs in-app. See exactly what the email looked like without relying on Resend delivery.',
    actions: [
      { href: '/admin/briefs', label: 'View Briefs', variant: 'primary' },
    ],
  },
  {
    title: 'Jobs',
    description: 'Manually trigger scout or brief runs. Useful for testing a new source without waiting for the cron.',
    actions: [
      { href: '/admin/jobs', label: 'Run Jobs', variant: 'primary' },
    ],
  },
  {
    title: 'Fact Checks',
    description: 'Claim-level fact-check drill-down. Surface the approve flag rate and whether flags are checker noise or bad data.',
    actions: [
      { href: '/admin/fact-checks', label: 'View Fact Checks', variant: 'primary' },
    ],
  },
  {
    title: 'System Errors',
    description: 'Background-job failures from scout, brief, and summarize. Resolve after investigating.',
    actions: [
      { href: '/admin/errors', label: 'View Errors', variant: 'primary' },
    ],
  },
]

const cardStyle: React.CSSProperties = {
  background: 'var(--color-background-soft)',
  border: '1px solid var(--color-border-soft)',
  borderRadius: 'var(--radius-card)',
  boxShadow: 'var(--shadow-soft)',
  padding: '1.5rem',
  display: 'flex',
  flexDirection: 'column',
  gap: '0.75rem',
}

const cardTitleStyle: React.CSSProperties = {
  margin: 0,
  fontFamily: 'var(--font-display)',
  fontSize: '1.5rem',
  color: 'var(--color-primary)',
}

const cardDescStyle: React.CSSProperties = {
  margin: 0,
  fontFamily: 'var(--font-body)',
  color: 'var(--color-text-secondary)',
  fontSize: '0.9375rem',
  lineHeight: 1.5,
  flex: 1,
}

const actionRowStyle: React.CSSProperties = {
  display: 'flex',
  flexWrap: 'wrap',
  gap: '0.5rem',
  marginTop: '0.25rem',
}

export default function AdminDashboard() {
  return (
    <div>
      <h1 style={{ marginBottom: '0.375rem' }}>Admin Dashboard</h1>
      <p
        style={{
          marginTop: 0,
          marginBottom: '2rem',
          fontFamily: 'var(--font-body)',
          color: 'var(--color-text-secondary)',
          fontSize: '0.9375rem',
        }}
      >
        Manage alerts, sources, programs, subscribers, and the content pipeline.
      </p>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
          gap: '1.25rem',
        }}
      >
        {SECTIONS.map((section) => (
          <section key={section.title} style={cardStyle}>
            <h2 style={cardTitleStyle}>{section.title}</h2>
            <p style={cardDescStyle}>{section.description}</p>
            <div style={actionRowStyle}>
              {section.actions.map((action) => (
                <Link
                  key={action.href}
                  href={action.href}
                  className={action.variant === 'secondary' ? 'rg-btn-secondary' : 'rg-btn-primary'}
                  style={{ display: 'inline-block' }}
                >
                  {action.label}
                </Link>
              ))}
            </div>
          </section>
        ))}
      </div>
    </div>
  )
}
