#!/usr/bin/env node
/**
 * seed-chart.mjs — JSON chart -> SQL migration
 *
 * Takes the JSON output of `extract-chart.mjs` and writes a SQL migration
 * that populates `programs.award_chart` with a clean markdown table.
 *
 * USAGE:
 *   node scripts/seed-chart.mjs --program=<slug> --input=/tmp/chart.json [--out=<migration-path>]
 *
 *   # End-to-end pipeline:
 *   node scripts/extract-chart.mjs --url=<url> --schema=scripts/schemas/<type>.json --out=/tmp/chart.json
 *   node scripts/seed-chart.mjs --program=<slug> --input=/tmp/chart.json
 *   supabase db query --linked --file <generated-migration>
 *
 * NOTES:
 * - Output is ASCII-only per feedback_ascii_only_in_sql_data.md (em-dashes
 *   and unicode quotes get mangled through the Supabase paste pipeline).
 * - Schema currently supports `airline-distance-banded-chart` shape only.
 *   Add new shapes by branching on a --shape flag if/when needed.
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

function parseArgs() {
  const args = { program: null, input: null, out: null }
  for (const a of process.argv.slice(2)) {
    if (a.startsWith('--program=')) args.program = a.slice('--program='.length)
    else if (a.startsWith('--input=')) args.input = a.slice('--input='.length)
    else if (a.startsWith('--out=')) args.out = a.slice('--out='.length)
  }
  if (!args.program || !args.input) {
    console.error('Usage: seed-chart.mjs --program=<slug> --input=<json-path> [--out=<sql-path>]')
    process.exit(1)
  }
  return args
}

function asciiize(s) {
  if (!s) return s
  return s
    .replace(/[–—]/g, '-')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/…/g, '...')
    .replace(/ /g, ' ')
}

function fmt(n) {
  if (n == null || n === 0) return '-'
  return n.toLocaleString('en-US')
}

function bandRow(b) {
  const cells = [
    asciiize(b.distance_band ?? ''),
    fmt(b.economy_points),
    fmt(b.premium_economy_points),
    fmt(b.business_points),
    fmt(b.first_points),
  ]
  return `| ${cells.join(' | ')} |`
}

function renderPartnerChart(chart) {
  const header = `### ${asciiize(chart.region_name)}\n\n`
  const scope = chart.scope_description ? `${asciiize(chart.scope_description)}\n\n` : ''
  const table = [
    '| Distance (miles) | Economy | Premium Economy | Business | First |',
    '| --- | --- | --- | --- | --- |',
    ...chart.bands.map(bandRow),
  ].join('\n')
  return header + scope + table
}

function renderOwnMetalChart(rows) {
  const header = `## Own-metal chart\n\nApplies to awards wholly on this program's own carrier(s).\n\n`
  const table = [
    '| Distance (miles) | Economy | Premium Economy | Business | First |',
    '| --- | --- | --- | --- | --- |',
    ...rows.map(bandRow),
  ].join('\n')
  return header + table
}

function renderChart(json) {
  const sections = []

  if (Array.isArray(json.partner_charts) && json.partner_charts.length) {
    sections.push('## Partner award charts\n\nDistance-banded by region. Points shown are starting-at; routes can price higher based on city pair, demand, segments, and partner availability.')
    for (const chart of json.partner_charts) sections.push(renderPartnerChart(chart))
  }

  if (Array.isArray(json.own_metal_chart) && json.own_metal_chart.length) {
    sections.push(renderOwnMetalChart(json.own_metal_chart))
  }

  if (json.booking_fees_summary) {
    sections.push(`## Booking and fees\n\n${asciiize(json.booking_fees_summary)}`)
  }

  return sections.join('\n\n')
}

function nextMigrationNumber() {
  const dir = 'supabase/migrations'
  const files = readdirSync(dir).filter((f) => /^\d{3}_/.test(f))
  const max = files
    .map((f) => parseInt(f.slice(0, 3), 10))
    .filter((n) => !Number.isNaN(n))
    .reduce((a, b) => Math.max(a, b), 0)
  return String(max + 1).padStart(3, '0')
}

function escapeSql(s) {
  return s.replace(/'/g, "''")
}

function buildMigration(program, chartMarkdown, sourceFile) {
  return `-- Auto-generated by scripts/seed-chart.mjs from ${sourceFile}
-- Populates programs.award_chart for ${program} with structured chart data
-- extracted via Firecrawl. ASCII-only per feedback_ascii_only_in_sql_data.md.

update programs
set award_chart = '${escapeSql(chartMarkdown)}'
where slug = '${program}';
`
}

function main() {
  const args = parseArgs()
  const json = JSON.parse(readFileSync(args.input, 'utf8'))
  const chart = renderChart(json)

  if (!chart.trim()) {
    console.error('No chart sections found in input JSON. Check the schema/output.')
    process.exit(1)
  }

  const num = nextMigrationNumber()
  const fname = args.out ?? `supabase/migrations/${num}_seed_${args.program}_chart.sql`
  const sql = buildMigration(args.program, chart, args.input)
  writeFileSync(fname, sql)
  console.log(`Wrote ${fname} (${chart.length} chars of chart markdown)`)
  console.log(`Apply with: supabase db query --linked --file ${fname}`)
}

main()
