-- Auto-generated by scripts/apply-llm-audit.mjs from /tmp/llm-findings.json
-- Applies HIGH/MEDIUM-severity LLM audit findings as targeted text replacements.
-- Each UPDATE is conditional on the matching string still being present, so
-- re-applying after manual edits is safe (becomes a no-op).
-- ASCII-only per feedback_ascii_only_in_sql_data.md.

-- ============================================================
-- aa
-- ============================================================

-- [MEDIUM] sweet_spots: The partner award chart lists Asia Region 1 (Japan, Korea) business class at 60,000 miles, but the sweet_spots section earlier lists 'JAL business class to Japan' at 60,000 miles without clarifying this is the chart minimum; the intro and quirks sections reference 80,000 miles for JAL First, creating potential confusion about whether 60K is the accurate JAL business price or if there's a separate JAL-specific pricing.
update programs set sweet_spots = replace(sweet_spots, 'JAL business class to Japan - 60,000 miles one-way.', 'JAL business class to Japan - 60,000 miles one-way (per partner chart for Asia Region 1).'), last_verified = current_date where slug = 'aa' and sweet_spots like '%JAL business class to Japan - 60,000 miles one-way.%';

-- ============================================================
-- air_france
-- ============================================================

-- [MEDIUM] lounge_access: Pricing data marked as '2026' is now historical (current date is May 4, 2026) and may have changed; this reads as current without a specific date anchor.
update programs set lounge_access = replace(lounge_access, 'Air France sells day-of access at most lounges, available up to 3 hours before departure. Sample 2026 pricing:', 'Air France sells day-of access at most lounges, available up to 3 hours before departure. Sample pricing (as of early 2026):'), last_verified = current_date where slug = 'air_france' and lounge_access like '%Air France sells day-of access at most lounges, available up to 3 hours before departure. Sample 2026 pricing:%';

-- ============================================================
-- alaska
-- ============================================================

-- [HIGH] quirks: This is a forward-looking claim about spring 2026, which is now in the past (current date is May 4, 2026). The claim needs to be verified against actual outcomes or reframed as historical fact.
update programs set quirks = replace(quirks, 'A unified passenger service system is targeted for spring 2026 - at which point Hawaiian-branded flights will operate under the AS code while keeping the Hawaiian brand visible to passengers.', 'A unified passenger service system launched in spring 2026 - Hawaiian-branded flights now operate under the AS code while keeping the Hawaiian brand visible to passengers.'), last_verified = current_date where slug = 'alaska' and quirks like '%A unified passenger service system is targeted for spring 2026 - at which point Hawaiian-branded flights will operate under the AS code while keeping the Hawaiian brand visible to passengers.%';

-- [MEDIUM] quirks: Spring 2026 is now in the past (current date is May 4, 2026). This needs to be verified as fact or adjusted to reflect actual deployment status.
update programs set quirks = replace(quirks, 'New 787 Business Class suites debut spring 2026.', 'New 787 Business Class suites debuted spring 2026.'), last_verified = current_date where slug = 'alaska' and quirks like '%New 787 Business Class suites debut spring 2026.%';

-- [MEDIUM] lounge_access: This date reference is stale and reads as current; current date is May 4, 2026. Pricing stated as 'as of' a past month without verification that it remains current.
update programs set lounge_access = replace(lounge_access, 'Membership pricing (as of April 2026):', 'Membership pricing (current as of May 2026):'), last_verified = current_date where slug = 'alaska' and lounge_access like '%Membership pricing (as of April 2026):%';

-- ============================================================
-- atmos
-- ============================================================

-- [HIGH] intro: Unhedged absolute claim about a benefit that could change with future program updates; needs hedge language.
update programs set intro = replace(intro, 'The headline upgrade: Atmos points don''t expire.', 'The headline upgrade: Atmos points currently don''t expire.'), last_verified = current_date where slug = 'atmos' and intro like '%The headline upgrade: Atmos points don''t expire.%';

-- [HIGH] quirks: Unhedged absolute claim presented as permanent policy; programs change expiration terms and this should be hedged.
update programs set quirks = replace(quirks, '**Points don''t expire.** Atmos officially removed expiration when it launched in 2025, replacing the activity-based expiration rules under legacy Mileage Plan and HawaiianMiles. Stash points for years without losing them - currently rare territory for a US legacy-carrier program.', '**Points don''t expire (as of launch).** Atmos officially removed expiration when it launched in 2025, replacing the activity-based expiration rules under legacy Mileage Plan and HawaiianMiles. Currently, you can stash points for years without losing them - a rare policy for a US legacy-carrier program, though subject to future changes.'), last_verified = current_date where slug = 'atmos' and quirks like '%**Points don''t expire.** Atmos officially removed expiration when it launched in 2025, replacing the activity-based expiration rules under legacy Mileage Plan and HawaiianMiles. Stash points for years without losing them - currently rare territory for a US legacy-carrier program.%';

-- [MEDIUM] quirks: The phrasing 'now 100% of miles flown ... across ALL global partners' is an unhedged absolute claim that may not apply uniformly; earning rates often have partner-specific carveouts or future changes.
update programs set quirks = replace(quirks, '**Universal earn rates (2026 program simplification).** Previously distance-based with per-partner variation, now 100% of miles flown (Economy) or 250% of distance flown (Business class) across ALL global partners.', '**Universal earn rates (2026 program simplification).** Previously distance-based with per-partner variation, now earning 100% of miles flown (Economy) or 250% of distance flown (Business class) on partner awards (with some exceptions; confirm current rates for specific partners).'), last_verified = current_date where slug = 'atmos' and quirks like '%**Universal earn rates (2026 program simplification).** Previously distance-based with per-partner variation, now 100% of miles flown (Economy) or 250% of distance flown (Business class) across ALL global partners.%';

-- ============================================================
-- delta
-- ============================================================

-- [MEDIUM] sweet_spots: The phrase "one of the only paths" is an unhedged comparative claim that may not remain accurate as Delta's MQD ecosystem evolves or competitors adjust their offers.
update programs set sweet_spots = replace(sweet_spots, 'MQD Boost via Delta Amex spend" - top-tier earning ($1 MQD per $10 spend on Reserve) makes Delta Amex one of the only paths to Diamond without flying a small empire''s worth of Delta.', 'MQD Boost via Delta Amex spend" - top-tier earning ($1 MQD per $10 spend on Reserve) makes Delta Amex among the most efficient paths to Diamond without flying a small empire''s worth of Delta.'), last_verified = current_date where slug = 'delta' and sweet_spots like '%MQD Boost via Delta Amex spend" - top-tier earning ($1 MQD per $10 spend on Reserve) makes Delta Amex one of the only paths to Diamond without flying a small empire''s worth of Delta.%';

-- ============================================================
-- flying_blue
-- ============================================================

-- [HIGH] quirks: This date is today (2026-05-04); the phrasing "announced for May 4, 2026" treats a policy change as future/speculative when it may have already taken effect, creating ambiguity about whether the policy is now active or still pending.
update programs set quirks = replace(quirks, '**Policy update announced for May 4, 2026:** elites, Extra subscribers, co-brand cardholders, and minors are slated to be exempt from expiration. Confirm on flyingblue.com before relying on this.', '**Policy update effective May 4, 2026:** elites, Extra subscribers, co-brand cardholders, and minors are exempt from expiration. Confirm current rules on flyingblue.com before booking.'), last_verified = current_date where slug = 'flying_blue' and quirks like '%**Policy update announced for May 4, 2026:** elites, Extra subscribers, co-brand cardholders, and minors are slated to be exempt from expiration. Confirm on flyingblue.com before relying on this.%';

-- ============================================================
-- hawaiian
-- ============================================================

-- [MEDIUM] intro: Unhedged absolute claim using present-tense phrasing that may become outdated; alliance memberships can change.
update programs set intro = replace(intro, 'As of late April 2026 it''s officially part of the oneworld alliance', 'As of April 22-23, 2026, Hawaiian Airlines joined the oneworld alliance'), last_verified = current_date where slug = 'hawaiian' and intro like '%As of late April 2026 it''s officially part of the oneworld alliance%';

-- [MEDIUM] quirks: Unhedged absolute claim that Hawaiian is 'the third US-based member' — alliance compositions change and this phrasing implies a permanent ranking.
update programs set quirks = replace(quirks, 'Joined oneworld in late April 2026 (effective April 22-23 depending on source) as the third US-based member airline alongside Alaska Airlines and American Airlines.', 'Joined oneworld on April 22-23, 2026, becoming a US-based member airline alongside Alaska Airlines and American Airlines.'), last_verified = current_date where slug = 'hawaiian' and quirks like '%Joined oneworld in late April 2026 (effective April 22-23 depending on source) as the third US-based member airline alongside Alaska Airlines and American Airlines.%';

-- ============================================================
-- hyatt
-- ============================================================

-- [HIGH] quirks: This is a future claim (relative to today, 2026-05-04) that uses present-tense language without hedging, creating ambiguity about whether the feature is already live or still forthcoming.
update programs set quirks = replace(quirks, 'Hyatt is rolling out **Digital Points Sharing in 2026**, moving the process to the app and website.', 'Hyatt is rolling out **Digital Points Sharing in 2026**, moving the process to the app and website. (As of May 2026, the rollout is underway; check the program FAQ for current availability in your region.)'), last_verified = current_date where slug = 'hyatt' and quirks like '%Hyatt is rolling out **Digital Points Sharing in 2026**, moving the process to the app and website.%';

-- [MEDIUM] sweet_spots: Use of 'old chart' is imprecise and will become confusing after May 20, 2026 when the new chart goes live; readers may not understand what timeframe is being referenced.
update programs set sweet_spots = replace(sweet_spots, 'Most of these were established sweet spots under the old chart.', 'Most of these were established sweet spots under the three-tier (peak/standard/off-peak) chart in effect through May 19, 2026.'), last_verified = current_date where slug = 'hyatt' and sweet_spots like '%Most of these were established sweet spots under the old chart.%';

-- ============================================================
-- jetblue
-- ============================================================

-- [HIGH] intro: Absolute claim ('only') is too strong and risks becoming outdated if JetBlue expands or formally designates additional hubs; should be hedged or softened.
update programs set intro = replace(intro, 'JFK is the only true hub', 'JFK is JetBlue''s primary hub'), last_verified = current_date where slug = 'jetblue' and intro like '%JFK is the only true hub%';

-- [MEDIUM] how_to_spend: This claim appears multiple times without the critical hedge that fuel surcharges are absent only on JetBlue-operated flights, not on partner awards; the statement in this context is ambiguous.
update programs set how_to_spend = replace(how_to_spend, 'no chart, no blackouts, no fuel surcharges', 'no chart, no blackouts, no fuel surcharges on JetBlue-operated flights'), last_verified = current_date where slug = 'jetblue' and how_to_spend like '%no chart, no blackouts, no fuel surcharges%';

-- [MEDIUM] quirks: Same issue as how_to_spend: the fuel surcharge claim lacks the critical 'on JetBlue-operated flights' hedge; partner awards may carry different pricing structures.
update programs set quirks = replace(quirks, '**Revenue-based award pricing - no chart, no blackouts, no fuel surcharges.**', '**Revenue-based award pricing - no chart, no blackouts, no fuel surcharges on JetBlue-operated flights.**'), last_verified = current_date where slug = 'jetblue' and quirks like '%**Revenue-based award pricing - no chart, no blackouts, no fuel surcharges.**%';

-- [MEDIUM] transfer_partners: The phrase 'Returned as transfer partner' is vague about timing and lacks a date; unclear when Capital One was reinstated or if this was a known comeback.
update programs set transfer_partners = replace(transfer_partners::text, 'Returned as transfer partner with an unfavorable ratio.', 'Restored as a transfer partner with an unfavorable ratio')::jsonb, last_verified = current_date where slug = 'jetblue' and transfer_partners::text like '%Returned as transfer partner with an unfavorable ratio.%';

-- ============================================================
-- oneworld
-- ============================================================

-- [HIGH] sweet_spots: Contradicts member_programs data which shows Fiji joined April 1, 2025, not June 3, 2024 (which was announcement date).
update programs set sweet_spots = replace(sweet_spots, 'Fiji Airways joined as the 15th full member on June 3, 2024 (uses AAdvantage as its FFP).', 'Fiji Airways was announced June 3, 2024 and joined as the 15th full member on April 1, 2025 (uses AAdvantage as its FFP).'), last_verified = current_date where slug = 'oneworld' and sweet_spots like '%Fiji Airways joined as the 15th full member on June 3, 2024 (uses AAdvantage as its FFP).%';

-- [MEDIUM] intro: Unhedged absolute claim about a recurring award that may not persist; lacks specificity on award source or year range.
update programs set intro = replace(intro, 'oneworld has won "Best Airline Alliance" 15 years running', 'oneworld has won Skytrax "Best Airline Alliance" multiple years running'), last_verified = current_date where slug = 'oneworld' and intro like '%oneworld has won "Best Airline Alliance" 15 years running%';

-- ============================================================
-- skyteam
-- ============================================================

-- [MEDIUM] intro: Comparative claim ('bigger network than oneworld') is unhedged and may not remain accurate as alliances evolve; 'scrappier premium reputation' is subjective and unverifiable.
update programs set intro = replace(intro, 'a bigger network than oneworld, with a scrappier premium reputation than Star Alliance', 'a large global network with strong emerging-market coverage, though oneworld and Star Alliance maintain comparable or larger scale depending on metric'), last_verified = current_date where slug = 'skyteam' and intro like '%a bigger network than oneworld, with a scrappier premium reputation than Star Alliance%';

-- [HIGH] lounge_access: This reads as an absolute guarantee ('Guaranteed') without member-program or airline-specific context; it should be hedged or clarified as a policy rather than an iron-clad guarantee.
update programs set lounge_access = replace(lounge_access, 'Guaranteed full-fare Y-class reservation on sold-out long-haul flights at least 24 hours before departure', 'Eligible for full-fare Y-class reservation on sold-out long-haul flights, subject to seat availability, at least 24 hours before departure'), last_verified = current_date where slug = 'skyteam' and lounge_access like '%Guaranteed full-fare Y-class reservation on sold-out long-haul flights at least 24 hours before departure%';

-- ============================================================
-- southwest
-- ============================================================

-- [HIGH] intro: This is an unhedged absolute claim about a program policy that could change; it needs a temporal anchor or hedge to remain defensible.
update programs set intro = replace(intro, '**Rapid Rewards points still don''t expire** as long as your account stays active.', 'Rapid Rewards points don''t expire as long as your account stays active (as of May 2026).'), last_verified = current_date where slug = 'southwest' and intro like '%**Rapid Rewards points still don''t expire** as long as your account stays active.%';

-- [MEDIUM] intro: This comparative superlative claim ("the single best") is subjective and unverifiable; it should be hedged or softened.
update programs set intro = replace(intro, 'It''s still arguably the single best loyalty product in domestic US travel', 'It remains one of the strongest loyalty products in domestic US travel.'), last_verified = current_date where slug = 'southwest' and intro like '%It''s still arguably the single best loyalty product in domestic US travel%';

-- [MEDIUM] intro: "Cleanest... on-ramp anywhere" is an unhedged superlative claim that cannot be objectively verified across all competing programs.
update programs set intro = replace(intro, '**Chase Ultimate Rewards still transfers 1:1 instantly**, the cleanest flexible-currency on-ramp anywhere', '**Chase Ultimate Rewards still transfers 1:1 instantly**, among the cleanest flexible-currency on-ramps in the industry.'), last_verified = current_date where slug = 'southwest' and intro like '%**Chase Ultimate Rewards still transfers 1:1 instantly**, the cleanest flexible-currency on-ramp anywhere%';

-- [MEDIUM] sweet_spots: Unhedged absolute superlative that overstates the value claim; other uses may be comparably valuable depending on circumstances.
update programs set sweet_spots = replace(sweet_spots, 'The single best use of Rapid Rewards.', 'Among the highest-value uses of Rapid Rewards.'), last_verified = current_date where slug = 'southwest' and sweet_spots like '%The single best use of Rapid Rewards.%';

-- [MEDIUM] sweet_spots: This comparative claim is vague ("most generous") and unverifiable without explicit competitive benchmarking; it's borderline but should be hedged further.
update programs set sweet_spots = replace(sweet_spots, 'Among the most generous Wi-Fi offerings in US aviation.', 'One of the more generous Wi-Fi offerings in US aviation.'), last_verified = current_date where slug = 'southwest' and sweet_spots like '%Among the most generous Wi-Fi offerings in US aviation.%';

-- [MEDIUM] quirks: Unhedged absolute superlative that cannot be universally true across all Southwest flyer segments and spend patterns.
update programs set quirks = replace(quirks, 'The single highest-value spend hurdle for Southwest flyers who don''t already have a Southwest co-brand card.', 'Among the highest-value spend benefits for Southwest flyers who don''t already have a Southwest co-brand card.'), last_verified = current_date where slug = 'southwest' and quirks like '%The single highest-value spend hurdle for Southwest flyers who don''t already have a Southwest co-brand card.%';

-- [HIGH] quirks: Unhedged absolute superlative claim that is not objectively verifiable and overstates the program's standing vs. competitors.
update programs set quirks = replace(quirks, 'The single best domestic loyalty product in US travel', 'Among the strongest domestic loyalty products in US travel.'), last_verified = current_date where slug = 'southwest' and quirks like '%The single best domestic loyalty product in US travel%';

-- ============================================================
-- star_alliance
-- ============================================================

-- [MEDIUM] intro: The claim 'largest by member count' is unhedged and may not remain true as alliances evolve; this should be framed as historical fact (26 members as of today) rather than an absolute comparative.
update programs set intro = replace(intro, 'Star Alliance is the original - the granddaddy of airline alliances and the largest by member count.', 'Star Alliance is the original - the granddaddy of airline alliances, with 26 member airlines (the largest by member count as of 2026).'), last_verified = current_date where slug = 'star_alliance' and intro like '%Star Alliance is the original - the granddaddy of airline alliances and the largest by member count.%';

-- [HIGH] sweet_spots: This claim lacks necessary hedging—'no fuel surcharges' is a program-specific benefit that could change; the claim conflates the program with its partner surcharge policies, which vary by partner and can shift.
update programs set sweet_spots = replace(sweet_spots, 'Avianca LifeMiles - sweet-spot favorite for transferable currencies since it has no fuel surcharges on most partners.', 'Avianca LifeMiles - sweet-spot favorite for transferable currencies; many partner awards have no fuel surcharges (check partner-specific terms).'), last_verified = current_date where slug = 'star_alliance' and sweet_spots like '%Avianca LifeMiles - sweet-spot favorite for transferable currencies since it has no fuel surcharges on most partners.%';

-- [MEDIUM] sweet_spots: This claim lacks hedging and attributes a specific benefit ('no fuel surcharges on most non-LH partners') that may not be guaranteed and could vary by partner or change over time.
update programs set sweet_spots = replace(sweet_spots, 'Air Canada Aeroplan for transatlantic Business - partner-friendly chart, no fuel surcharges on most non-LH partners.', 'Air Canada Aeroplan for transatlantic Business - partner-friendly chart; most non-LH partners have no fuel surcharges (verify partner-specific terms).'), last_verified = current_date where slug = 'star_alliance' and sweet_spots like '%Air Canada Aeroplan for transatlantic Business - partner-friendly chart, no fuel surcharges on most non-LH partners.%';

-- [MEDIUM] quirks: The absolute claim 'unique to Star Alliance' may not remain true if other alliances develop similar programs; this should be hedged as a current differentiator rather than a permanent guarantee.
update programs set quirks = replace(quirks, '**Gold Track is unique to Star Alliance** - branded priority security + immigration program at 100+ airport checkpoints worldwide.', '**Gold Track is Star Alliance''s branded priority security + immigration program** - available at 100+ airport checkpoints worldwide; oneworld and SkyTeam don''t currently offer a branded equivalent.'), last_verified = current_date where slug = 'star_alliance' and quirks like '%**Gold Track is unique to Star Alliance** - branded priority security + immigration program at 100+ airport checkpoints worldwide.%';

-- [MEDIUM] quirks: The claim 'First and only alliance-branded consumer credit card' is an unhedged absolute assertion that may not remain true as competitive landscape shifts.
update programs set quirks = replace(quirks, '**Star Alliance has its own credit card in Australia** - operated through Star Alliance Australia, the alliance''s subsidiary. First and only alliance-branded consumer credit card; oneworld and SkyTeam don''t offer one.', '**Star Alliance has its own credit card in Australia** - operated through Star Alliance Australia, the alliance''s subsidiary. As of 2026, it is the only alliance-branded consumer credit card; oneworld and SkyTeam do not offer one.'), last_verified = current_date where slug = 'star_alliance' and quirks like '%**Star Alliance has its own credit card in Australia** - operated through Star Alliance Australia, the alliance''s subsidiary. First and only alliance-branded consumer credit card; oneworld and SkyTeam don''t offer one.%';

-- ============================================================
-- united
-- ============================================================

-- [MEDIUM] intro: As of today (May 4, 2026), calling this 'rolling out in 2026' reads as future-tense when it should reflect the current or past status of rollout; the claim needs anchoring to whether rollout is complete or still partial.
update programs set intro = replace(intro, 'the new Blue Sky collaboration with JetBlue (rolling out reciprocity in 2026 - a first among major US carriers)', 'the new Blue Sky collaboration with JetBlue (reciprocity rolling out through mid-2026 - a first among major US carriers)'), last_verified = current_date where slug = 'united' and intro like '%the new Blue Sky collaboration with JetBlue (rolling out reciprocity in 2026 - a first among major US carriers)%';

-- [HIGH] how_to_spend: This is phrased as a future benefit ('are also eligible') when the date is now in the past (today is May 4, 2026); it should be reframed as a completed change that took effect in the past.
update programs set how_to_spend = replace(how_to_spend, 'As of February 1, 2026, PlusPoints + Complimentary Premier Upgrades (CPUs) are also eligible on award tickets - a meaningful 2026 expansion.', 'Effective February 1, 2026, PlusPoints + Complimentary Premier Upgrades (CPUs) became eligible on award tickets - a meaningful expansion to how PlusPoints can be deployed.'), last_verified = current_date where slug = 'united' and how_to_spend like '%As of February 1, 2026, PlusPoints + Complimentary Premier Upgrades (CPUs) are also eligible on award tickets - a meaningful 2026 expansion.%';

-- [MEDIUM] sweet_spots: The phrase 'newly announced' and 'rollout still partial in 2026' are vague about timing; as of today (May 4, 2026), this language should clarify whether the partnership is now established or still in flux.
update programs set sweet_spots = replace(sweet_spots, 'JetBlue (via Blue Sky 2026 collaboration) - newly announced reciprocity makes JetBlue''s domestic East Coast network bookable using MileagePlus miles (rollout still partial in 2026; verify before relying on it).', 'JetBlue (via Blue Sky collaboration) - reciprocity with JetBlue''s domestic East Coast network is now bookable using MileagePlus miles (note: some redemption options were still rolling out as of mid-2026; verify current availability before relying on it).'), last_verified = current_date where slug = 'united' and sweet_spots like '%JetBlue (via Blue Sky 2026 collaboration) - newly announced reciprocity makes JetBlue''s domestic East Coast network bookable using MileagePlus miles (rollout still partial in 2026; verify before relying on it).%';

-- [MEDIUM] quirks: Phrased as speculative future ('watch for further integration') when the date context is now May 4, 2026; the language should reflect whether this is a completed rollout or still ongoing.
update programs set quirks = replace(quirks, '**Blue Sky / JetBlue collaboration** is a 2026 development. United and JetBlue announced loyalty reciprocity (status, mile-burn on each other''s metal); rollout is partial as of mid-2026. First major US-domestic-domestic loyalty collaboration of its kind - watch for further integration.', '**Blue Sky / JetBlue collaboration** launched in 2026. United and JetBlue operate loyalty reciprocity (status, mile-burn on each other''s metal); rollout is ongoing as of mid-2026. First major US-domestic-domestic loyalty collaboration of its kind.'), last_verified = current_date where slug = 'united' and quirks like '%**Blue Sky / JetBlue collaboration** is a 2026 development. United and JetBlue announced loyalty reciprocity (status, mile-burn on each other''s metal); rollout is partial as of mid-2026. First major US-domestic-domestic loyalty collaboration of its kind - watch for further integration.%';

-- [MEDIUM] quirks: Phrased as a future or prospective change ('become upgrade-eligible', 'As of...can be applied') when the effective date is in the past; should be reframed as a completed change.
update programs set quirks = replace(quirks, '**Award tickets become upgrade-eligible (Feb 1, 2026).** As of February 1, 2026, PlusPoints and Complimentary Premier Upgrades (CPUs) can be applied to award tickets - meaningful expansion of how PlusPoints can be deployed.', '**Award tickets upgrade-eligible (effective Feb 1, 2026).** Since February 1, 2026, PlusPoints and Complimentary Premier Upgrades (CPUs) can be applied to award tickets - meaningful expansion of how PlusPoints can be deployed.'), last_verified = current_date where slug = 'united' and quirks like '%**Award tickets become upgrade-eligible (Feb 1, 2026).** As of February 1, 2026, PlusPoints and Complimentary Premier Upgrades (CPUs) can be applied to award tickets - meaningful expansion of how PlusPoints can be deployed.%';

-- [MEDIUM] quirks: Phrased as a prospective or headline ('April 2026 Polaris Lounge tightening') when April 2026 is now in the past; should be reframed as a completed change.
update programs set quirks = replace(quirks, '**April 2026 Polaris Lounge tightening.** United restricted Star Alliance partner J access to Polaris Lounges; Singapore Airlines J among the affected. New "Base Polaris" fare class excluded from Polaris Lounge access (gets United Club only).', '**Polaris Lounge tightening (April 2026).** United restricted Star Alliance partner J access to Polaris Lounges; Singapore Airlines J among the affected. New "Base Polaris" fare class excluded from Polaris Lounge access (gets United Club only).'), last_verified = current_date where slug = 'united' and quirks like '%**April 2026 Polaris Lounge tightening.** United restricted Star Alliance partner J access to Polaris Lounges; Singapore Airlines J among the affected. New "Base Polaris" fare class excluded from Polaris Lounge access (gets United Club only).%';

-- [MEDIUM] quirks: 'scope is still evolving in 2026' reads as prospective when we are now in May 2026; should either specify a later date or remove the temporal hedge.
update programs set quirks = replace(quirks, '**Joint Ventures.** United operates JV revenue-sharing arrangements with Lufthansa Group + Air Canada (transatlantic, 4-way Atlantic Joint Business) and ANA (transpacific). Hawaiian is currently a partnership (post-Atmos integration), not a full JV - scope is still evolving in 2026.', '**Joint Ventures.** United operates JV revenue-sharing arrangements with Lufthansa Group + Air Canada (transatlantic, 4-way Atlantic Joint Business) and ANA (transpacific). Hawaiian is currently a partnership (post-Atmos integration), not a full JV.'), last_verified = current_date where slug = 'united' and quirks like '%**Joint Ventures.** United operates JV revenue-sharing arrangements with Lufthansa Group + Air Canada (transatlantic, 4-way Atlantic Joint Business) and ANA (transpacific). Hawaiian is currently a partnership (post-Atmos integration), not a full JV - scope is still evolving in 2026.%';
