-- Auto-generated by scripts/apply-llm-audit.mjs from /tmp/llm-findings-2.json
-- Applies HIGH/MEDIUM-severity LLM audit findings as targeted text replacements.
-- Each UPDATE is conditional on the matching string still being present, so
-- re-applying after manual edits is safe (becomes a no-op).
-- ASCII-only per feedback_ascii_only_in_sql_data.md.

-- ============================================================
-- aa
-- ============================================================

-- [MEDIUM] sweet_spots: The partner award chart in award_chart section lists Asia Region 1 (Japan, Korea) business at 60,000 miles, but this specific claim lacks context; it should match the chart or be removed for consistency.
update programs set sweet_spots = replace(sweet_spots, 'JAL business class to Japan - 60,000 miles one-way.', 'JAL business class to Japan - 60,000 miles one-way (Asia Region 1 pricing).'), last_verified = current_date where slug = 'aa' and sweet_spots like '%JAL business class to Japan - 60,000 miles one-way.%';

-- [HIGH] sweet_spots: This is an unhedged absolute claim that Finnair is always surcharge-free; carrier practices can change without notice, and surcharge policies are outside AA's control.
update programs set sweet_spots = replace(sweet_spots, 'Finnair is the surcharge-free workaround at the same mile price.', 'Finnair typically carries no fuel surcharges at the same mile price - verify current surcharge status on aa.com.'), last_verified = current_date where slug = 'aa' and sweet_spots like '%Finnair is the surcharge-free workaround at the same mile price.%';

-- [HIGH] award_chart: The claim that Finnair is 'surcharge-free' is an unhedged absolute; carrier surcharge policies can change and are outside AA's control.
update programs set award_chart = replace(award_chart, 'British Airways carries punishing carrier-imposed fuel surcharges on award tickets - expect $500-1,000+ in surcharges on a transatlantic business award. Finnair is the surcharge-free workaround at the same mile price.', 'British Airways carries punishing carrier-imposed fuel surcharges on award tickets - expect $500-1,000+ in surcharges on a transatlantic business award. Finnair typically carries no fuel surcharges at the same mile price, but verify current surcharge status on aa.com.'), last_verified = current_date where slug = 'aa' and award_chart like '%British Airways carries punishing carrier-imposed fuel surcharges on award tickets - expect $500-1,000+ in surcharges on a transatlantic business award. Finnair is the surcharge-free workaround at the same mile price.%';

-- ============================================================
-- air_france
-- ============================================================

-- [MEDIUM] lounge_access: Date reference 'early 2026' is now in the past relative to today (2026-05-04) and reads stale without a specific month; pricing may have changed since then.
update programs set lounge_access = replace(lounge_access, 'Sample pricing (as of early 2026):', 'Sample pricing (as of April 2026):'), last_verified = current_date where slug = 'air_france' and lounge_access like '%Sample pricing (as of early 2026):%';

-- ============================================================
-- alaska
-- ============================================================

-- [HIGH] quirks: This is a future-looking claim (spring 2026) written as a firm target from a 2026-05-04 perspective, but 'spring 2026' may have already passed or be in progress; the claim reads unhedged about delivery timing.
update programs set quirks = replace(quirks, 'A unified passenger service system is targeted for spring 2026 - at which point Hawaiian-branded flights will operate under the AS code while keeping the Hawaiian brand visible to passengers.', 'A unified passenger service system was targeted for spring 2026 - at which point Hawaiian-branded flights will operate under the AS code while keeping the Hawaiian brand visible to passengers.'), last_verified = current_date where slug = 'alaska' and quirks like '%A unified passenger service system is targeted for spring 2026 - at which point Hawaiian-branded flights will operate under the AS code while keeping the Hawaiian brand visible to passengers.%';

-- [MEDIUM] quirks: From the 2026-05-04 perspective, 'spring 2026' has either just ended or is current; this phrasing is vague about whether the debut is complete or ongoing, and may read stale if accessed later in 2026.
update programs set quirks = replace(quirks, 'New 787 Business Class suites debuted spring 2026.', 'New 787 Business Class suites debuted in spring 2026.'), last_verified = current_date where slug = 'alaska' and quirks like '%New 787 Business Class suites debuted spring 2026.%';

-- ============================================================
-- atmos
-- ============================================================

-- [HIGH] intro: Unhedged absolute claim about a policy that could change; lacks temporal hedge or explicit caveat that this is subject to program terms.
update programs set intro = replace(intro, 'Atmos points currently don''t expire.', 'Atmos points currently don''t expire - a major shift for a US legacy carrier and rare in the industry, though the program reserves the right to change expiration policy.'), last_verified = current_date where slug = 'atmos' and intro like '%Atmos points currently don''t expire.%';

-- [MEDIUM] sweet_spots: Comparative superlative ('standout') without hedging; difficult to verify as objectively true across all competitive programs.
update programs set sweet_spots = replace(sweet_spots, 'Among the standout business-class redemptions to Asia for points hobbyists.', 'A standout business-class redemption to Asia for points hobbyists.'), last_verified = current_date where slug = 'atmos' and sweet_spots like '%Among the standout business-class redemptions to Asia for points hobbyists.%';

-- [HIGH] quirks: The second sentence is an unhedged absolute claim about future behavior ('without losing them'); expiration policies can change and should be hedged.
update programs set quirks = replace(quirks, 'Atmos officially removed expiration when it launched in 2025, replacing the activity-based expiration rules under legacy Mileage Plan and HawaiianMiles. Stash points for years without losing them - currently rare territory for a US legacy-carrier program.', 'Atmos officially removed expiration when it launched in 2025, replacing the activity-based expiration rules under legacy Mileage Plan and HawaiianMiles. You can stash points for years without losing them under current program terms - currently rare territory for a US legacy-carrier program.'), last_verified = current_date where slug = 'atmos' and quirks like '%Atmos officially removed expiration when it launched in 2025, replacing the activity-based expiration rules under legacy Mileage Plan and HawaiianMiles. Stash points for years without losing them - currently rare territory for a US legacy-carrier program.%';

-- [MEDIUM] quirks: Subjective value claim ('worth learning') without hedging; overstates objective program merit.
update programs set quirks = replace(quirks, 'This is the structural advantage that makes the program worth learning.', 'This is the structural advantage that makes the program potentially valuable for distance-chart learners.'), last_verified = current_date where slug = 'atmos' and quirks like '%This is the structural advantage that makes the program worth learning.%';

-- [MEDIUM] quirks: The claim 'now earning 100% of miles flown' and '250% of distance flown' is stated as current fact but may not be true for all partner combinations; the parenthetical caveat is insufficient hedging for the main claim.
update programs set quirks = replace(quirks, 'Universal earn rates (2026 program simplification). Previously distance-based with per-partner variation, now earning 100% of miles flown (Economy) or 250% of distance flown (Business class) on partner awards (with some exceptions; confirm current rates for specific partners).', 'Universal earn rates (2026 program simplification). Previously distance-based with per-partner variation, Atmos moved toward earning approximately 100% of miles flown (Economy) or 250% of distance flown (Business class) on most partner awards, though rates vary by partner; confirm current rates for your specific booking.'), last_verified = current_date where slug = 'atmos' and quirks like '%Universal earn rates (2026 program simplification). Previously distance-based with per-partner variation, now earning 100% of miles flown (Economy) or 250% of distance flown (Business class) on partner awards (with some exceptions; confirm current rates for specific partners).%';

-- [MEDIUM] lounge_access: Specific price point ('around $60') will drift and become stale; should be hedged or removed to avoid editorial staleness.
update programs set lounge_access = replace(lounge_access, 'Day passes: Alaska Lounge sells single-visit day passes (around $60) at the door, subject to capacity, valid same-day with a ticketed boarding pass for any Alaska or partner flight departing that day.', 'Day passes: Alaska Lounge sells single-visit day passes at the door (pricing typically $50-$75 range), subject to capacity, valid same-day with a ticketed boarding pass for any Alaska or partner flight departing that day.'), last_verified = current_date where slug = 'atmos' and lounge_access like '%Day passes: Alaska Lounge sells single-visit day passes (around $60) at the door, subject to capacity, valid same-day with a ticketed boarding pass for any Alaska or partner flight departing that day.%';

-- ============================================================
-- delta
-- ============================================================

-- [MEDIUM] sweet_spots: Unhedged absolute claim ('one of the only paths') is too strong and may not remain true if Delta or competitors introduce alternative MQD pathways.
update programs set sweet_spots = replace(sweet_spots, 'MQD Boost via Delta Amex spend" - top-tier earning ($1 MQD per $10 spend on Reserve) makes Delta Amex one of the only paths to Diamond without flying a small empire''s worth of Delta.', 'MQD Boost via Delta Amex spend" - top-tier earning ($1 MQD per $10 spend on Reserve) makes Delta Amex a strong path to Diamond without flying extensively on Delta.'), last_verified = current_date where slug = 'delta' and sweet_spots like '%MQD Boost via Delta Amex spend" - top-tier earning ($1 MQD per $10 spend on Reserve) makes Delta Amex one of the only paths to Diamond without flying a small empire''s worth of Delta.%';

-- [MEDIUM] quirks: This is an unhedged absolute claim. While SkyMiles currently don't expire, no airline program guarantees perpetual non-expiration policies—they can be changed by the carrier. It needs hedging.
update programs set quirks = replace(quirks, 'Delta SkyMiles never expire.', 'Delta SkyMiles currently never expire.'), last_verified = current_date where slug = 'delta' and quirks like '%Delta SkyMiles never expire.%';

-- ============================================================
-- flying_blue
-- ============================================================

-- [HIGH] transfer_partners: Unhedged absolute claim about Wells Fargo's award-hold policy across all WF partners — this is difficult to verify and may not remain accurate as partnerships evolve.
update programs set transfer_partners = replace(transfer_partners::text, 'Flying Blue is one of the few WF partners that allows award holds before transfer', 'Earned via Wells Fargo Autograph cards. Typically near-instant; allow up to 72h. Award holds before transfer may be available (confirm with Wells Fargo).')::jsonb, last_verified = current_date where slug = 'flying_blue' and transfer_partners::text like '%Flying Blue is one of the few WF partners that allows award holds before transfer%';

-- ============================================================
-- hawaiian
-- ============================================================

-- [HIGH] intro: This is stated as a past fact, but the date (April 22-23, 2026) is in the future relative to today (May 4, 2026); the claim should be written in past tense as a completed event since it has already occurred.
update programs set intro = replace(intro, 'As of April 22-23, 2026, Hawaiian Airlines joined the oneworld alliance - the third US-based member alongside Alaska and American.', 'Hawaiian Airlines joined the oneworld alliance on April 22-23, 2026 - the third US-based member alongside Alaska and American.'), last_verified = current_date where slug = 'hawaiian' and intro like '%As of April 22-23, 2026, Hawaiian Airlines joined the oneworld alliance - the third US-based member alongside Alaska and American.%';

-- ============================================================
-- hyatt
-- ============================================================

-- [MEDIUM] intro: This is an unhedged comparative claim that cannot be verified across all programs and may shift with market conditions; 'typically' is weak hedging for a superlative comparison.
update programs set intro = replace(intro, 'the points are typically the most valuable hotel currency for US-based travelers', 'the points are often considered among the most valuable hotel currency for US-based travelers'), last_verified = current_date where slug = 'hyatt' and intro like '%the points are typically the most valuable hotel currency for US-based travelers%';

-- [HIGH] quirks: The phrase 'As of May 2026' treats a future date (the content audit date is May 4, 2026, but the statement implies ongoing status through May 2026) as a historical anchor, creating ambiguity about what 'current' means on a page that will be read after May 2026.
update programs set quirks = replace(quirks, 'Hyatt is rolling out **Digital Points Sharing in 2026**, moving the process to the app and website. (As of May 2026, the rollout is underway; check the program FAQ for current availability in your region.)', 'Hyatt is rolling out **Digital Points Sharing in 2026**, moving the process to the app and website. (Rollout timing varies by region; check the program FAQ for current availability in your region.)'), last_verified = current_date where slug = 'hyatt' and quirks like '%Hyatt is rolling out **Digital Points Sharing in 2026**, moving the process to the app and website. (As of May 2026, the rollout is underway; check the program FAQ for current availability in your region.)%';

-- ============================================================
-- jetblue
-- ============================================================

-- [MEDIUM] intro: Today is May 4, 2026; the claim uses present tense for a future or ongoing event that may not have been publicly announced yet.
update programs set intro = replace(intro, 'Spirit announced in May 2026 that it will cease to exist', 'Spirit announced in May 2026 that it will cease operations.'), last_verified = current_date where slug = 'jetblue' and intro like '%Spirit announced in May 2026 that it will cease to exist%';

-- [HIGH] how_to_spend: This claim appears without the necessary partner-specific context — it's unhedged and could imply no fuel surcharges on all award bookings, when the promise only applies to JetBlue-operated metal.
update programs set how_to_spend = replace(how_to_spend, 'no fuel surcharges on JetBlue-operated flights', 'no fuel surcharges on JetBlue-operated flights (partner awards may vary)'), last_verified = current_date where slug = 'jetblue' and how_to_spend like '%no fuel surcharges on JetBlue-operated flights%';

-- [HIGH] sweet_spots: This claim could be misread as an absolute statement about JetBlue's structure rather than a comparison; the phrasing 'JetBlue metal' is clear, but the sentence structure invites misinterpretation.
update programs set sweet_spots = replace(sweet_spots, 'No fuel surcharges on JetBlue metal - unlike British Airways or Lufthansa partner awards, JetBlue-operated flights only charge taxes ($5.60 per US segment).', 'No fuel surcharges on JetBlue-operated flights - unlike British Airways or Lufthansa partner awards, you only pay taxes ($5.60 per US segment) on JetBlue metal.'), last_verified = current_date where slug = 'jetblue' and sweet_spots like '%No fuel surcharges on JetBlue metal - unlike British Airways or Lufthansa partner awards, JetBlue-operated flights only charge taxes ($5.60 per US segment).%';

-- [MEDIUM] award_chart: Today is May 4, 2026; referencing 'TPG May 2026 valuation' is imprecise and may refer to a future or not-yet-published valuation.
update programs set award_chart = replace(award_chart, 'TPG May 2026 valuation pegs TrueBlue at 1.35 cpp.', 'TPG''s recent 2026 valuation pegs TrueBlue at 1.35 cpp.'), last_verified = current_date where slug = 'jetblue' and award_chart like '%TPG May 2026 valuation pegs TrueBlue at 1.35 cpp.%';

-- [MEDIUM] transfer_partners: The word 'Restored' is unhedged and unverified — no date or source confirms when Capital One was 'restored' or from what prior state.
update programs set transfer_partners = replace(transfer_partners::text, 'Restored as a transfer partner with an unfavorable ratio Generally a poor value transfer; use Capital One Travel portal at 1 cpp instead, or save for foreign carrier transfers where the ratio is 1:1.', 'Available as a transfer partner at an unfavorable ratio. Generally a poor value transfer; use Capital One Travel portal at 1 cpp instead, or save for foreign carrier transfers where the ratio is 1:1.')::jsonb, last_verified = current_date where slug = 'jetblue' and transfer_partners::text like '%Restored as a transfer partner with an unfavorable ratio Generally a poor value transfer; use Capital One Travel portal at 1 cpp instead, or save for foreign carrier transfers where the ratio is 1:1.%';

-- ============================================================
-- oneworld
-- ============================================================

-- [HIGH] sweet_spots: The intro states Fiji Airways joined as the 15th full member, but the member_programs data shows joined date as 2025-04-01 (April 1, 2025), not June 3, 2024. June 3, 2024 was the announcement date; membership became effective April 1, 2025.
update programs set sweet_spots = replace(sweet_spots, 'Fiji Airways joined as the 15th full member on June 3, 2024 (uses AAdvantage as its FFP).', 'Fiji Airways joined as the 15th full member on April 1, 2025 (announced June 3, 2024; uses AAdvantage as its FFP).'), last_verified = current_date where slug = 'oneworld' and sweet_spots like '%Fiji Airways joined as the 15th full member on June 3, 2024 (uses AAdvantage as its FFP).%';

-- [HIGH] quirks: The member_programs data shows Fiji Airways joined on April 1, 2025, not June 3, 2024. June 3, 2024 was the announcement date; membership became effective April 1, 2025.
update programs set quirks = replace(quirks, 'Fiji Airways joined as the 15th full member on June 3, 2024 (uses AAdvantage as its FFP).', 'Fiji Airways joined as the 15th full member on April 1, 2025 (announced June 3, 2024; uses AAdvantage as its FFP).'), last_verified = current_date where slug = 'oneworld' and quirks like '%Fiji Airways joined as the 15th full member on June 3, 2024 (uses AAdvantage as its FFP).%';

-- ============================================================
-- skyteam
-- ============================================================

-- [MEDIUM] intro: This is an unhedged absolute comparative claim ('simpler than oneworld's three') that assumes oneworld's tier structure remains static; oneworld could change its tier count, making this claim false.
update programs set intro = replace(intro, 'The alliance has only **two** elite tiers (Elite Plus and Elite - simpler than oneworld''s three)', 'The alliance has only **two** elite tiers (Elite Plus and Elite - simpler than oneworld''s current three-tier structure)'), last_verified = current_date where slug = 'skyteam' and intro like '%The alliance has only **two** elite tiers (Elite Plus and Elite - simpler than oneworld''s three)%';

-- [MEDIUM] lounge_access: This is presented as a current, blanket rule without hedge; lounge policies can change and vary by specific lounges. The source attribution at the end ('*Source: SkyTeam lounge access policy...*') mitigates but doesn't fully address the risk of this becoming outdated.
update programs set lounge_access = replace(lounge_access, '**Entry window:** minimum 3 hours prior to scheduled departure at the lounge of your departure airport.', '**Entry window:** typically minimum 3 hours prior to scheduled departure at the lounge of your departure airport; check the SkyTeam Lounge Finder for specific lounge policies.'), last_verified = current_date where slug = 'skyteam' and lounge_access like '%**Entry window:** minimum 3 hours prior to scheduled departure at the lounge of your departure airport.%';

-- [MEDIUM] lounge_access: The label '(NEW April 1, 2025)' is now stale as of 2026-05-04; it no longer meaningfully communicates 'new' since over a year has passed. This should be updated to reflect the change as implemented rather than marked as 'new'.
update programs set lounge_access = replace(lounge_access, '**Domestic-only itineraries (NEW April 1, 2025):** Elite Plus members now enjoy access at select domestic lounges when traveling on a SkyTeam member airline, even on domestic-only itineraries.', '**Domestic-only itineraries (effective April 1, 2025):** Elite Plus members now enjoy access at select domestic lounges when traveling on a SkyTeam member airline, even on domestic-only itineraries.'), last_verified = current_date where slug = 'skyteam' and lounge_access like '%**Domestic-only itineraries (NEW April 1, 2025):** Elite Plus members now enjoy access at select domestic lounges when traveling on a SkyTeam member airline, even on domestic-only itineraries.%';

-- ============================================================
-- southwest
-- ============================================================

-- [MEDIUM] intro: The claim lacks the critical caveat that UR transfers do NOT count toward Companion Pass or A-List qualification, which is mentioned later but should be flagged here to avoid reader confusion about redemption value.
update programs set intro = replace(intro, 'Chase Ultimate Rewards still transfers 1:1 instantly', 'Chase Ultimate Rewards still transfers 1:1 instantly (though transfers do not count toward Companion Pass or A-List Tier Qualifying Points - only Southwest co-brand card spend and revenue flights earn CPQP/TQPs)'), last_verified = current_date where slug = 'southwest' and intro like '%Chase Ultimate Rewards still transfers 1:1 instantly%';

-- [HIGH] tier_benefits: This is a factual contradiction within the tier benefits for A-List Preferred—the benefit should not be listed as an A-List Preferred exclusive if it applies to all members, and the note contradicts the listing.
update programs set tier_benefits = replace(tier_benefits::text, 'Free in-flight Wi-Fi (note: free Wi-Fi is actually offered to ALL Rapid Rewards Members)', 'Remove this benefit from the A-List Preferred list entirely, since free Wi-Fi is a universal Rapid Rewards member benefit, not a tier-exclusive perk.')::jsonb, last_verified = current_date where slug = 'southwest' and tier_benefits::text like '%Free in-flight Wi-Fi (note: free Wi-Fi is actually offered to ALL Rapid Rewards Members)%';

-- ============================================================
-- star_alliance
-- ============================================================

-- [MEDIUM] intro: Unhedged absolute claim that may not survive competitive scrutiny; 'original' is debatable depending on how you define 'alliance' (Oneworld predates Star Alliance's current structure).
update programs set intro = replace(intro, 'Star Alliance is the original - the granddaddy of airline alliances', 'Star Alliance, founded in 1997, is among the oldest airline alliances'), last_verified = current_date where slug = 'star_alliance' and intro like '%Star Alliance is the original - the granddaddy of airline alliances%';

-- [HIGH] intro: Internal contradiction: the intro states 'first Asia lounge' for T3, but the lounge_access section clarifies that the original Guangzhou location opened November 21, 2024 as the first Asia lounge, and T3 opened April 28, 2026. The intro is misleading as written.
update programs set intro = replace(intro, 'Six dedicated Star Alliance lounges (LAX, GIG, EZE, CDG, GRU, and Guangzhou Baiyun T3 - the alliance''s first Asia lounge).', 'Six dedicated Star Alliance lounges (LAX, GIG, EZE, CDG, GRU, and Guangzhou Baiyun T3 - the alliance''s second Asia lounge, following the original Guangzhou location opened in November 2024).'), last_verified = current_date where slug = 'star_alliance' and intro like '%Six dedicated Star Alliance lounges (LAX, GIG, EZE, CDG, GRU, and Guangzhou Baiyun T3 - the alliance''s first Asia lounge).%';

-- [HIGH] sweet_spots: Unhedged claim about fuel surcharges without partner-specific context; surcharge policies vary by partner and change over time. 'Most partners' is vague and not verifiable.
update programs set sweet_spots = replace(sweet_spots, 'Avianca LifeMiles - sweet-spot favorite for transferable currencies since it has no fuel surcharges on most partners.', 'Avianca LifeMiles - sweet-spot favorite for transferable currencies; many (though not all) Star Alliance partners have no fuel surcharges on LifeMiles awards.'), last_verified = current_date where slug = 'star_alliance' and sweet_spots like '%Avianca LifeMiles - sweet-spot favorite for transferable currencies since it has no fuel surcharges on most partners.%';

-- [HIGH] sweet_spots: Unhedged claim about fuel surcharges without partner-specific context; surcharge policies vary by partner and change over time.
update programs set sweet_spots = replace(sweet_spots, 'Air Canada Aeroplan for transatlantic Business - partner-friendly chart, no fuel surcharges on most non-LH partners.', 'Air Canada Aeroplan for transatlantic Business - partner-friendly chart with reduced or no fuel surcharges on many non-LH partners.'), last_verified = current_date where slug = 'star_alliance' and sweet_spots like '%Air Canada Aeroplan for transatlantic Business - partner-friendly chart, no fuel surcharges on most non-LH partners.%';

-- [MEDIUM] quirks: Unhedged absolute claim that Gold Track is 'unique'; this may not remain true if competitors launch similar programs, or the claim may be contestable.
update programs set quirks = replace(quirks, '**Gold Track is unique to Star Alliance** - branded priority security + immigration program at 100+ airport checkpoints worldwide.', '**Gold Track is Star Alliance-exclusive** - branded priority security + immigration program at 100+ airport checkpoints worldwide. Oneworld and SkyTeam do not currently offer an equivalent branded program.'), last_verified = current_date where slug = 'star_alliance' and quirks like '%**Gold Track is unique to Star Alliance** - branded priority security + immigration program at 100+ airport checkpoints worldwide.%';

-- [MEDIUM] quirks: Unhedged absolute claim ('first and only') that may not remain true if competitors launch cards; also lacks date anchor (as of 2026) for forward-looking statement.
update programs set quirks = replace(quirks, '**Star Alliance has its own credit card in Australia** - operated through Star Alliance Australia, the alliance''s subsidiary. First and only alliance-branded consumer credit card; oneworld and SkyTeam don''t offer one.', '**Star Alliance has its own credit card in Australia** - operated through Star Alliance Australia, the alliance''s subsidiary. As of 2026, it is the only alliance-branded consumer credit card among the three major alliances; oneworld and SkyTeam do not currently offer one.'), last_verified = current_date where slug = 'star_alliance' and quirks like '%**Star Alliance has its own credit card in Australia** - operated through Star Alliance Australia, the alliance''s subsidiary. First and only alliance-branded consumer credit card; oneworld and SkyTeam don''t offer one.%';

-- ============================================================
-- united
-- ============================================================

-- [MEDIUM] intro: Unhedged absolute claim about Blue Sky/JetBlue being 'first' — this is a superlative claim that may not remain true or may be challenged by competitors; needs hedging or removal.
update programs set intro = replace(intro, 'a first among major US carriers', 'among the first major US carriers to launch reciprocal loyalty integration with a domestic competitor'), last_verified = current_date where slug = 'united' and intro like '%a first among major US carriers%';

-- [MEDIUM] quirks: Unhedged absolute superlative claim ('first') that is both difficult to verify and may become outdated if competitors follow; needs hedging.
update programs set quirks = replace(quirks, 'First major US-domestic-domestic loyalty collaboration of its kind', 'among the first major US-domestic loyalty collaborations of its kind'), last_verified = current_date where slug = 'united' and quirks like '%First major US-domestic-domestic loyalty collaboration of its kind%';
