-- Auto-generated by scripts/apply-llm-audit.mjs from /tmp/sonnet-findings.json
-- Applies HIGH/MEDIUM-severity LLM audit findings as targeted text replacements.
-- Each UPDATE is conditional on the matching string still being present, so
-- re-applying after manual edits is safe (becomes a no-op).
-- ASCII-only per feedback_ascii_only_in_sql_data.md.

-- ============================================================
-- aa
-- ============================================================

-- [HIGH] intro: Unhedged absolute superlative claim about fleet and passenger size that can change without notice and is not anchored to a specific year or source.
update programs set intro = replace(intro, 'American Airlines is the world''s largest carrier by fleet and passengers', 'American Airlines has ranked among the world''s largest carriers by fleet and passengers'), last_verified = current_date where slug = 'aa' and intro like '%American Airlines is the world''s largest carrier by fleet and passengers%';

-- [MEDIUM] intro: Unhedged absolute historical claim that is accurate but stated as a current identifier; 'founding' is verifiable but 'US member' framing could be misread as an exclusive current status worth clarifying.
update programs set intro = replace(intro, 'the founding US member of oneworld', 'a founding member of oneworld'), last_verified = current_date where slug = 'aa' and intro like '%the founding US member of oneworld%';

-- [MEDIUM] sweet_spots: Absolute claim that Finnair carries no surcharges; carrier-imposed surcharge policies can change without notice and this is not hedged.
update programs set sweet_spots = replace(sweet_spots, 'Finnair is the surcharge-free workaround', 'Finnair has historically been the surcharge-free workaround (verify current surcharge levels at booking)'), last_verified = current_date where slug = 'aa' and sweet_spots like '%Finnair is the surcharge-free workaround%';

-- [MEDIUM] award_chart: Absolute claim that Finnair carries no surcharges; carrier-imposed surcharge policies can change without notice and this is not hedged.
update programs set award_chart = replace(award_chart, 'Finnair is the surcharge-free workaround', 'Finnair has historically been the surcharge-free workaround (verify current surcharge levels at booking)'), last_verified = current_date where slug = 'aa' and award_chart like '%Finnair is the surcharge-free workaround%';

-- ============================================================
-- air_france
-- ============================================================

-- [HIGH] quirks: These are future dates (after today, 2026-05-04) stated as confirmed facts with no hedging, but the rollout has not yet occurred and schedules can change.
update programs set quirks = replace(quirks, 'Houston (Jul 6, 2026), and Boston (Jul 20, 2026). All JFK and LAX flights converted to the new suite by July 2026.', 'Houston (scheduled Jul 6, 2026), and Boston (scheduled Jul 20, 2026). All JFK and LAX flights are targeted for conversion to the new suite by July 2026.'), last_verified = current_date where slug = 'air_france' and quirks like '%Houston (Jul 6, 2026), and Boston (Jul 20, 2026). All JFK and LAX flights converted to the new suite by July 2026.%';

-- [HIGH] quirks: This is a future, unhedged absolute claim about a specific network that has not yet taken effect as of today (2026-05-04) and is subject to change before summer 2026.
update programs set quirks = replace(quirks, 'Effective summer 2026, the network covers 14 destinations from Paris-CDG: Abidjan, Atlanta, Boston, Dubai, Houston, Los Angeles, Miami, New York-JFK, San Francisco, São Paulo, Singapore, Tel Aviv, Tokyo-Haneda, and Washington, D.C.', 'From summer 2026, La Première is scheduled to cover 14 destinations from Paris-CDG: Abidjan, Atlanta, Boston, Dubai, Houston, Los Angeles, Miami, New York-JFK, San Francisco, São Paulo, Singapore, Tel Aviv, Tokyo-Haneda, and Washington, D.C. Verify current schedules with Air France, as routes are subject to change.'), last_verified = current_date where slug = 'air_france' and quirks like '%Effective summer 2026, the network covers 14 destinations from Paris-CDG: Abidjan, Atlanta, Boston, Dubai, Houston, Los Angeles, Miami, New York-JFK, San Francisco, São Paulo, Singapore, Tel Aviv, Tokyo-Haneda, and Washington, D.C.%';

-- ============================================================
-- atmos
-- ============================================================

-- [MEDIUM] intro: The sentence 'That's a major shift for a US legacy carrier' is a verbatim near-duplicate of the hedged clause immediately before it, creating a redundant unhedged restatement after the hedge was already applied.
update programs set intro = replace(intro, 'Atmos points currently don''t expire - a major shift for a US legacy carrier and rare in the industry, though the program reserves the right to change expiration policy. That''s a major shift for a US legacy carrier', 'Atmos points currently don''t expire - rare in the industry for a US legacy carrier, though the program reserves the right to change expiration policy.'), last_verified = current_date where slug = 'atmos' and intro like '%Atmos points currently don''t expire - a major shift for a US legacy carrier and rare in the industry, though the program reserves the right to change expiration policy. That''s a major shift for a US legacy carrier%';

-- [HIGH] sweet_spots: Unhedged superlative comparative claim that may not stay true as other programs adjust inter-island pricing.
update programs set sweet_spots = replace(sweet_spots, 'Best inter-island award rate available.', 'Among the strongest inter-island award rates available.'), last_verified = current_date where slug = 'atmos' and sweet_spots like '%Best inter-island award rate available.%';

-- [MEDIUM] sweet_spots: Unanchored comparative claim ('one of the strongest') without hedging that partner rules or program terms could change.
update programs set sweet_spots = replace(sweet_spots, 'This rule survived the merger and is still one of the strongest in US-airline points.', 'This rule survived the merger and, as of 2026, remains one of the strongest stopover policies in US-airline points - though partner award rules can change without notice.'), last_verified = current_date where slug = 'atmos' and sweet_spots like '%This rule survived the merger and is still one of the strongest in US-airline points.%';

-- [MEDIUM] quirks: Unhedged comparative superlative claim that is stale-prone and unverifiable against all programs.
update programs set quirks = replace(quirks, 'one of the cleanest 2026 program structures in points.', 'one of the more straightforward earning structures among US-airline loyalty programs in 2026.'), last_verified = current_date where slug = 'atmos' and quirks like '%one of the cleanest 2026 program structures in points.%';

-- [HIGH] quirks: An annual fee for a co-brand card is mentioned on a program page; card annual fee details belong on the card's own page, not here.
update programs set quirks = replace(quirks, 'Only Atmos Rewards Summit Visa Infinite cardholders can pool points with family or friends. Free-tier members and Ascent cardholders cannot pool. If pooling matters to your strategy, the Summit''s annual fee becomes the cost of entry.', 'Only Atmos Rewards Summit Visa Infinite cardholders can pool points with family or friends. Free-tier members and Ascent cardholders cannot pool. If pooling matters to your strategy, Summit card eligibility is the cost of entry - see the Summit card page for current fee details.'), last_verified = current_date where slug = 'atmos' and quirks like '%Only Atmos Rewards Summit Visa Infinite cardholders can pool points with family or friends. Free-tier members and Ascent cardholders cannot pool. If pooling matters to your strategy, the Summit''s annual fee becomes the cost of entry.%';

-- [MEDIUM] lounge_access: A specific dollar amount for a day pass is a fast-drifting factual claim that should be hedged or removed from a program page.
update programs set lounge_access = replace(lounge_access, 'Alaska Lounge sells single-visit day passes (around $60) at the door', 'Alaska Lounge sells single-visit day passes at the door (price subject to change; check alaskaair.com for current rates)'), last_verified = current_date where slug = 'atmos' and lounge_access like '%Alaska Lounge sells single-visit day passes (around $60) at the door%';

-- [HIGH] lounge_access: Specific card benefit quantities (8 passes, 8 Wi-Fi passes) for a co-brand card are card-page details that drift quickly and belong on the card page, not a program page.
update programs set lounge_access = replace(lounge_access, 'Atmos Rewards Summit Visa Infinite** (Bank of America) - 8 Alaska Lounge single-visit passes per year + 8 lounge Wi-Fi passes', '**Atmos Rewards Summit Visa Infinite** (Bank of America) - annual Alaska Lounge single-visit passes and lounge Wi-Fi passes (see the Summit card page for current quantities)'), last_verified = current_date where slug = 'atmos' and lounge_access like '%Atmos Rewards Summit Visa Infinite** (Bank of America) - 8 Alaska Lounge single-visit passes per year + 8 lounge Wi-Fi passes%';

-- ============================================================
-- delta
-- ============================================================

-- [MEDIUM] quirks: Unhedged absolute claim about a program policy that can change at any time without notice.
update programs set quirks = replace(quirks, 'Delta SkyMiles currently never expire.', 'Delta SkyMiles currently have no expiration policy - though this can change, so check Delta''s terms before banking on it.'), last_verified = current_date where slug = 'delta' and quirks like '%Delta SkyMiles currently never expire.%';

-- [MEDIUM] quirks: This references a future Medallion Year (2027) as settled fact based on a Dec 2025 announcement — Delta could announce further changes before the 2026 qualification year closes; the claim should be hedged as current policy subject to change.
update programs set quirks = replace(quirks, '2027 thresholds (earned via 2026 spend) remain unchanged from 2026 per Delta''s Dec 2025 announcement.', '2027 thresholds (earned via 2026 spend) were announced as unchanged from 2026 in Delta''s Dec 2025 communication - confirm at delta.com/medallion as the qualification year progresses.'), last_verified = current_date where slug = 'delta' and quirks like '%2027 thresholds (earned via 2026 spend) remain unchanged from 2026 per Delta''s Dec 2025 announcement.%';

-- [HIGH] lounge_access: Specific lounge count is a fast-drifting fact that will go stale as Delta opens or closes locations; it is stated without hedging or a source date.
update programs set lounge_access = replace(lounge_access, 'Delta operates ~50+ Sky Club lounges worldwide', 'Delta operates a large and growing network of Sky Club lounges worldwide (count current as of publication - check delta.com/skyclub for the latest)'), last_verified = current_date where slug = 'delta' and lounge_access like '%Delta operates ~50+ Sky Club lounges worldwide%';

-- [HIGH] lounge_access: Delta has been actively expanding Delta One Lounges; stating exactly three locations with specific airports is a fast-drifting fact that may already be outdated.
update programs set lounge_access = replace(lounge_access, 'three Delta One Lounges (BOS, JFK, LAX)', 'Delta One Lounges (currently at select major hubs including BOS, JFK, and LAX - check delta.com for the latest locations)'), last_verified = current_date where slug = 'delta' and lounge_access like '%three Delta One Lounges (BOS, JFK, LAX)%';

-- [MEDIUM] lounge_access: The unnamed 'Premium Lounge' reference is unverifiable without a location or proper name, creating an unverifiable claim that readers cannot act on.
update programs set lounge_access = replace(lounge_access, 'a separate Premium Lounge', 'additional premium lounge offerings at select airports'), last_verified = current_date where slug = 'delta' and lounge_access like '%a separate Premium Lounge%';

-- [HIGH] lounge_access: Specific card visit caps, per-visit fees, guest pass counts, and spend thresholds are card-level details that belong on the card page, not the program page — and they drift quickly.
update programs set lounge_access = replace(lounge_access, 'Delta SkyMiles Reserve / Reserve Business Amex | 15 visits per Medallion Year (Feb 1 - Jan 31); $50/visit ($25 Grab and Go) once cap exhausted; **unlimited unlocked at $75K calendar-year spend**; +2 guests at $50, plus 4 One-Time Guest Passes per year (max 2 per visit)', 'Delta SkyMiles Reserve / Reserve Business Amex | Limited Sky Club visits per Medallion Year; per-visit fee applies once cap is exhausted; unlimited visits unlockable via calendar-year spend threshold; guest passes included - see card page for current terms'), last_verified = current_date where slug = 'delta' and lounge_access like '%Delta SkyMiles Reserve / Reserve Business Amex | 15 visits per Medallion Year (Feb 1 - Jan 31); $50/visit ($25 Grab and Go) once cap exhausted; **unlimited unlocked at $75K calendar-year spend**; +2 guests at $50, plus 4 One-Time Guest Passes per year (max 2 per visit)%';

-- [HIGH] lounge_access: Specific card visit caps, per-visit fees, and spend thresholds are card-level details that belong on the card page, not the program page.
update programs set lounge_access = replace(lounge_access, 'Delta SkyMiles Platinum / Business Platinum Amex (US-issued) | 10 visits per Medallion Year; $50/visit after cap; **unlimited unlocked at $75K calendar-year spend**', 'Delta SkyMiles Platinum / Business Platinum Amex (US-issued) | Limited Sky Club visits per Medallion Year; per-visit fee applies once cap is exhausted; unlimited visits unlockable via calendar-year spend threshold - see card page for current terms'), last_verified = current_date where slug = 'delta' and lounge_access like '%Delta SkyMiles Platinum / Business Platinum Amex (US-issued) | 10 visits per Medallion Year; $50/visit after cap; **unlimited unlocked at $75K calendar-year spend**%';

-- [MEDIUM] lounge_access: Specific card visit allotments are card-level details that belong on the card page, not the program page, and are subject to change.
update programs set lounge_access = replace(lounge_access, 'Delta SkyMiles Diners Club Card | 3 complimentary visits or 3 individuals per calendar year', 'Delta SkyMiles Diners Club Card | Complimentary visits per calendar year - see card page for current terms'), last_verified = current_date where slug = 'delta' and lounge_access like '%Delta SkyMiles Diners Club Card | 3 complimentary visits or 3 individuals per calendar year%';

-- [MEDIUM] lounge_access: Specific card visit allotments are card-level details that belong on the card page, not the program page, and are subject to change.
update programs set lounge_access = replace(lounge_access, 'Delta SkyMiles TRUST CLUB Platinum VISA | 6 complimentary visits or 6 individuals per calendar year', 'Delta SkyMiles TRUST CLUB Platinum VISA | Complimentary visits per calendar year - see card page for current terms'), last_verified = current_date where slug = 'delta' and lounge_access like '%Delta SkyMiles TRUST CLUB Platinum VISA | 6 complimentary visits or 6 individuals per calendar year%';

-- [MEDIUM] lounge_access: Specific card visit allotments are card-level details that belong on the card page, not the program page, and are subject to change.
update programs set lounge_access = replace(lounge_access, 'Delta SkyMiles TRUST CLUB Gold VISA | 3 complimentary visits or 3 individuals per calendar year', 'Delta SkyMiles TRUST CLUB Gold VISA | Complimentary visits per calendar year - see card page for current terms'), last_verified = current_date where slug = 'delta' and lounge_access like '%Delta SkyMiles TRUST CLUB Gold VISA | 3 complimentary visits or 3 individuals per calendar year%';

-- [MEDIUM] sweet_spots: Specific mile threshold for a dynamic-priced award is stated without a date anchor and will go stale as pricing shifts; even with 'occasionally' it implies a reproducible data point.
update programs set sweet_spots = replace(sweet_spots, 'occasionally surfaces at sub-50K each way on off-peak dates', 'occasionally surfaces at notably lower prices each way on off-peak dates - check current pricing, as dynamic awards fluctuate'), last_verified = current_date where slug = 'delta' and sweet_spots like '%occasionally surfaces at sub-50K each way on off-peak dates%';

-- [HIGH] quirks: 'Atmos' is not a real airline — this appears to be a drafting error for Alaska Airlines in the context of the Alaska/Hawaiian merger.
update programs set quirks = replace(quirks, 'When flying Hawaiian metal under the post-merger Alaska / Atmos crossover, Sky Club access only applies on Delta-marketed flights - not Hawaiian-marketed.', 'When flying Hawaiian metal under the post-merger Alaska/Hawaiian crossover, Sky Club access only applies on Delta-marketed flights - not Hawaiian-marketed.'), last_verified = current_date where slug = 'delta' and quirks like '%When flying Hawaiian metal under the post-merger Alaska / Atmos crossover, Sky Club access only applies on Delta-marketed flights - not Hawaiian-marketed.%';

-- ============================================================
-- flying_blue
-- ============================================================

-- [MEDIUM] intro: Unhedged comparative claim ('widest') that is not anchored to a specific date or source and may not remain accurate as programs add or lose partners.
update programs set intro = replace(intro, 'one of the widest 1:1 transfer-partner lineups around', 'a broad 1:1 transfer-partner lineup'), last_verified = current_date where slug = 'flying_blue' and intro like '%one of the widest 1:1 transfer-partner lineups around%';

-- ============================================================
-- jetblue
-- ============================================================

-- [MEDIUM] award_chart: Aer Lingus and Singapore Airlines are listed as active redemption partners here, but the quirks section correctly categorizes Aer Lingus as codeshare-only (no points) and Singapore Airlines as an earn-only partner — this list conflates earn-only and codeshare partners with true redemption partners, which is factually inconsistent.
update programs set award_chart = replace(award_chart, 'Active partners as of May 2026: United (via Blue Sky), Aer Lingus, Etihad, Qatar Airways, Singapore Airlines, Icelandair, Cape Air, China Airlines.', 'Active redemption partners as of May 2026: United (via Blue Sky), Etihad, Qatar Airways, Cape Air, China Airlines. Earn-only partners (credit miles to TrueBlue, no redemption): Singapore Airlines, Icelandair. Codeshare only (no points either direction): Aer Lingus.'), last_verified = current_date where slug = 'jetblue' and award_chart like '%Active partners as of May 2026: United (via Blue Sky), Aer Lingus, Etihad, Qatar Airways, Singapore Airlines, Icelandair, Cape Air, China Airlines.%';

-- [MEDIUM] intro: This is an unhedged comparative superlative claim that may not stay true and is not verifiable as of any fixed date.
update programs set intro = replace(intro, 'The flexible-currency on-ramp is the broadest of any US program', 'The flexible-currency on-ramp is among the broadest of any US program'), last_verified = current_date where slug = 'jetblue' and intro like '%The flexible-currency on-ramp is the broadest of any US program%';

-- ============================================================
-- klm
-- ============================================================

-- [MEDIUM] quirks: Unhedged superlative comparative claim ('a leader') about market position that is unverifiable without a source and may not remain accurate.
update programs set quirks = replace(quirks, 'The group is a leader in intercontinental traffic departing from Europe.', 'The group has historically ranked among the largest carriers for intercontinental traffic departing from Europe.'), last_verified = current_date where slug = 'klm' and quirks like '%The group is a leader in intercontinental traffic departing from Europe.%';

-- ============================================================
-- oneworld
-- ============================================================

-- [MEDIUM] intro: Specific destination and territory counts drift frequently as member airlines adjust networks; this is stated as an absolute current fact without hedging.
update programs set intro = replace(intro, '15 member airlines flying to 900+ destinations across 170 territories', 'roughly 15 member airlines flying to 900+ destinations across 170+ territories (figures subject to change)'), last_verified = current_date where slug = 'oneworld' and intro like '%15 member airlines flying to 900+ destinations across 170 territories%';

-- [MEDIUM] intro: Cumulative passenger figures grow continuously and this specific number will become stale without hedging or a reference year.
update programs set intro = replace(intro, 'counts roughly 9 billion passengers carried since founding', 'had counted roughly 9 billion passengers carried since founding as of early 2026'), last_verified = current_date where slug = 'oneworld' and intro like '%counts roughly 9 billion passengers carried since founding%';

-- [HIGH] sweet_spots: Specific award pricing is unhedged and award charts change; stating a precise mileage range as fact without a date anchor or hedge will mislead readers when rates change.
update programs set sweet_spots = replace(sweet_spots, 'book through AAdvantage at 70K-95K one-way', 'book through AAdvantage (rates have historically run in the 70K-95K one-way range - verify current chart before booking)'), last_verified = current_date where slug = 'oneworld' and sweet_spots like '%book through AAdvantage at 70K-95K one-way%';

-- [HIGH] sweet_spots: Both the specific mileage price and the superlative claim ('easily the cheapest way') are unhedged absolutes that can become stale or inaccurate as partner award charts change.
update programs set sweet_spots = replace(sweet_spots, '80K Atmos miles one-way, easily the cheapest way into the JAL First product', 'historically around 80K Atmos miles one-way - one of the lowest-cost ways into the JAL First product (verify current chart before booking)'), last_verified = current_date where slug = 'oneworld' and sweet_spots like '%80K Atmos miles one-way, easily the cheapest way into the JAL First product%';

-- [HIGH] sweet_spots: Both the 'virtually no fuel surcharges' claim for Iberia and the specific ~$1,000 YQ figure for BA are unhedged and drift with airline surcharge policies.
update programs set sweet_spots = replace(sweet_spots, 'book through Iberia Club using Avios with virtually no fuel surcharges, vs. BA''s ~$1,000 in YQ on the same metal', 'book through Iberia Club using Avios with historically low fuel surcharges, vs. BA''s substantial YQ fees (often ~$700-1,000+) on the same metal - confirm current surcharge levels before booking'), last_verified = current_date where slug = 'oneworld' and sweet_spots like '%book through Iberia Club using Avios with virtually no fuel surcharges, vs. BA''s ~$1,000 in YQ on the same metal%';

-- [MEDIUM] sweet_spots: This is an unhedged absolute directional claim about BA short-haul Avios pricing that is confusingly worded — BA's peak/off-peak chart applies to short-haul, not transatlantic, and stating Europe-to-US rates 'can be astronomical' under a short-haul bullet is factually misleading.
update programs set sweet_spots = replace(sweet_spots, 'can be astronomical for Europe to US', 'off-peak rates can be a genuine bargain for short European hops, but peak pricing can be steep; transatlantic Avios rates are a separate, distance-based calculation'), last_verified = current_date where slug = 'oneworld' and sweet_spots like '%can be astronomical for Europe to US%';

-- [MEDIUM] member_programs: The 'first and only' claim is an unhedged absolute that will become false if another African carrier joins oneworld.
update programs set member_programs = replace(member_programs::text, 'First and only African full member.', 'As of 2026, the only African full member.')::jsonb, last_verified = current_date where slug = 'oneworld' and member_programs::text like '%First and only African full member.%';

-- ============================================================
-- skyteam
-- ============================================================

-- [MEDIUM] quirks: Unhedged comparative claim about SkyPriority vs. oneworld's priority programs that is subjective and unverifiable without a current source.
update programs set quirks = replace(quirks, 'More cohesively rolled out than oneworld''s equivalent priority programs.', 'Generally considered more uniformly implemented than oneworld''s equivalent priority programs, though rollout quality varies by airport.'), last_verified = current_date where slug = 'skyteam' and quirks like '%More cohesively rolled out than oneworld''s equivalent priority programs.%';

-- ============================================================
-- southwest
-- ============================================================

-- [MEDIUM] intro: Unhedged absolute claim that no other US carrier offers transatlantic redemptions on own metal without partner awards is a stale comparative that could easily be inaccurate or become inaccurate; it also conflates Southwest's Iceland launch as uniquely non-partner when other carriers operate their own transatlantic metal too.
update programs set intro = replace(intro, 'Southwest''s first transatlantic flying - its own metal to Iceland (BWI-KEF launching 2026, BNA-KEF following) - opens a new redemption frontier no other US carrier offers without partner awards.', 'Southwest''s first transatlantic flying - its own metal to Iceland (BWI-KEF launching 2026, BNA-KEF following) - opens a new redemption frontier for the program.'), last_verified = current_date where slug = 'southwest' and intro like '%Southwest''s first transatlantic flying - its own metal to Iceland (BWI-KEF launching 2026, BNA-KEF following) - opens a new redemption frontier no other US carrier offers without partner awards.%';

-- [MEDIUM] tier_benefits: Unhedged superlative comparative claim ('the single best') in a tier benefits list item is not hedged and cannot be verified or sustained.
update programs set tier_benefits = replace(tier_benefits::text, 'The single best domestic loyalty product in US travel', 'Among the strongest domestic loyalty products in US travel')::jsonb, last_verified = current_date where slug = 'southwest' and tier_benefits::text like '%The single best domestic loyalty product in US travel%';

-- ============================================================
-- star_alliance
-- ============================================================

-- [MEDIUM] sweet_spots: Unhedged fuel-surcharge claim without partner-specific context; LifeMiles surcharge policies vary by partner and can change without notice.
update programs set sweet_spots = replace(sweet_spots, 'Avianca LifeMiles - sweet-spot favorite for transferable currencies since it has no fuel surcharges on most partners.', 'Avianca LifeMiles - sweet-spot favorite for transferable currencies; historically no fuel surcharges on most partners, though policies vary by partner and can change - verify before booking.'), last_verified = current_date where slug = 'star_alliance' and sweet_spots like '%Avianca LifeMiles - sweet-spot favorite for transferable currencies since it has no fuel surcharges on most partners.%';

-- [MEDIUM] sweet_spots: Unhedged fuel-surcharge claim without partner-specific context; Aeroplan surcharge policies can change and vary by carrier.
update programs set sweet_spots = replace(sweet_spots, 'Air Canada Aeroplan for transatlantic Business - partner-friendly chart, no fuel surcharges on most non-LH partners.', 'Air Canada Aeroplan for transatlantic Business - partner-friendly chart; historically no fuel surcharges on most non-LH partners, though policies vary by carrier and can change - verify before booking.'), last_verified = current_date where slug = 'star_alliance' and sweet_spots like '%Air Canada Aeroplan for transatlantic Business - partner-friendly chart, no fuel surcharges on most non-LH partners.%';

-- [HIGH] quirks: Absolute competitive claim ('unique to Star Alliance', 'oneworld and SkyTeam don't have an equivalent') that may become stale if competing alliances launch similar programs.
update programs set quirks = replace(quirks, 'Gold Track is unique to Star Alliance - branded priority security + immigration program at 100+ airport checkpoints worldwide. Available to Star Gold members and First/Business customers on any Star Alliance flight. oneworld and SkyTeam don''t have an equivalent branded program.', 'Gold Track is Star Alliance''s branded priority security + immigration program at 100+ airport checkpoints worldwide. Available to Star Gold members and First/Business customers on any Star Alliance flight. As of mid-2026, oneworld and SkyTeam do not offer an equivalent alliance-branded program.'), last_verified = current_date where slug = 'star_alliance' and quirks like '%Gold Track is unique to Star Alliance - branded priority security + immigration program at 100+ airport checkpoints worldwide. Available to Star Gold members and First/Business customers on any Star Alliance flight. oneworld and SkyTeam don''t have an equivalent branded program.%';

-- [MEDIUM] quirks: Superlative competitive claim ('most destinations of any airline in the world') that drifts quickly as route networks change.
update programs set quirks = replace(quirks, 'Most destinations of any airline in the world (300+).', 'Among the most destinations of any airline in the world (300+).'), last_verified = current_date where slug = 'star_alliance' and quirks like '%Most destinations of any airline in the world (300+).%';

-- [HIGH] intro: Factually misleading — individual frequent-flyer programmes each have their own earn/status structures; alliance Gold/Silver status is a recognition tier mapped from member programme tiers, not a single pooled earning system.
update programs set intro = replace(intro, 'all earn into the same Gold / Silver alliance status', 'all map to the same Gold / Silver alliance status recognition tiers'), last_verified = current_date where slug = 'star_alliance' and intro like '%all earn into the same Gold / Silver alliance status%';

-- [MEDIUM] member_programs: Superlative competitive claim that drifts quickly as route networks change across airlines.
update programs set member_programs = replace(member_programs::text, 'Most destinations of any airline in the world (300+).', 'Among the most destinations of any airline in the world (300+).')::jsonb, last_verified = current_date where slug = 'star_alliance' and member_programs::text like '%Most destinations of any airline in the world (300+).%';

-- ============================================================
-- united
-- ============================================================

-- [MEDIUM] intro: Unhedged comparative claim about network size that can change as airlines adjust routes and is not anchored to a specific verified date.
update programs set intro = replace(intro, 'broader international network than American', 'historically a broader international network than American'), last_verified = current_date where slug = 'united' and intro like '%broader international network than American%';

-- [MEDIUM] intro: The specific member count of Star Alliance changes as airlines join or leave; stating '26' as a fixed fact without hedging will become stale.
update programs set intro = replace(intro, 'deep partner inventory across all 26 Star Alliance members', 'deep partner inventory across Star Alliance members (26 as of 2026)'), last_verified = current_date where slug = 'united' and intro like '%deep partner inventory across all 26 Star Alliance members%';

-- [MEDIUM] quirks: Unhedged 'among the first' comparative claim that is unverifiable and could be stale or inaccurate.
update programs set quirks = replace(quirks, 'among the first major US-domestic loyalty collaborations of its kind - watch for further integration.', 'one of the more notable US-domestic loyalty collaborations of its kind - watch for further integration.'), last_verified = current_date where slug = 'united' and quirks like '%among the first major US-domestic loyalty collaborations of its kind - watch for further integration.%';

-- [MEDIUM] lounge_access: Specific card annual fee ranges ($650–$1,000+) belong on card pages, not program pages, and will drift quickly.
update programs set lounge_access = replace(lounge_access, 'Annual purchase ($650-$1,000+ tier-dependent); also accessible via Chase Sapphire Reserve United Club Card', 'Annual purchase (fee varies by membership tier); also accessible via select United co-branded credit cards - see card pages for current fees'), last_verified = current_date where slug = 'united' and lounge_access like '%Annual purchase ($650-$1,000+ tier-dependent); also accessible via Chase Sapphire Reserve United Club Card%';
