-- Auto-generated by scripts/apply-llm-audit.mjs from /tmp/marriott-findings.json
-- Applies HIGH/MEDIUM-severity LLM audit findings as targeted text replacements.
-- Each UPDATE is conditional on the matching string still being present, so
-- re-applying after manual edits is safe (becomes a no-op).
-- ASCII-only per feedback_ascii_only_in_sql_data.md.

-- ============================================================
-- marriott-bonvoy
-- ============================================================

-- [MEDIUM] quirks: Unhedged forward-looking claim about a future policy continuation that may not be confirmed or may change — needs hedging since it refers to future program behavior.
update programs set quirks = replace(quirks, 'Marriott has indicated this policy continues into the 2026 membership year.', 'Marriott has indicated this policy may continue into the 2026 membership year, but check official Bonvoy communications for confirmation.'), last_verified = current_date where slug = 'marriott-bonvoy' and quirks like '%Marriott has indicated this policy continues into the 2026 membership year.%';

-- [MEDIUM] sweet_spots: Third-party valuation figures drift frequently and this references a future date (mid-2026 is after today, 2026-05-04), making it an unverifiable forward-dated claim rather than a confirmed historical fact.
update programs set sweet_spots = replace(sweet_spots, 'TPG''s mid-2026 valuation puts Bonvoy points around 0.7 cpp on average', 'Third-party valuations (e.g. TPG) have recently pegged Bonvoy points around 0.7 cpp on average - sweet spots beat the average; do not assume cash rates make all redemptions winners.'), last_verified = current_date where slug = 'marriott-bonvoy' and sweet_spots like '%TPG''s mid-2026 valuation puts Bonvoy points around 0.7 cpp on average%';

-- [MEDIUM] award_chart: Mid-2026 is after today (2026-05-04), so labeling these observations as 'mid-2026' presents a future date as a current or past reference, which is unverifiable and misleading.
update programs set award_chart = replace(award_chart, 'Frequent Miler empirical observations as of mid-2026', 'Frequent Miler empirical observations as of early 2026'), last_verified = current_date where slug = 'marriott-bonvoy' and award_chart like '%Frequent Miler empirical observations as of mid-2026%';
