-- Auto-generated by scripts/apply-llm-audit.mjs from /tmp/marriott-findings.json
-- Applies HIGH/MEDIUM-severity LLM audit findings as targeted text replacements.
-- Each UPDATE is conditional on the matching string still being present, so
-- re-applying after manual edits is safe (becomes a no-op).
-- ASCII-only per feedback_ascii_only_in_sql_data.md.

-- ============================================================
-- marriott-bonvoy
-- ============================================================

-- [MEDIUM] sweet_spots: 'Recently' is an unanchored time reference that will become stale without a specific date or year.
update programs set sweet_spots = replace(sweet_spots, 'Third-party valuations (e.g. TPG) have recently pegged Bonvoy points around 0.7 cpp on average', 'Third-party valuations (e.g. TPG) have pegged Bonvoy points around 0.7 cpp on average as of early 2026'), last_verified = current_date where slug = 'marriott-bonvoy' and sweet_spots like '%Third-party valuations (e.g. TPG) have recently pegged Bonvoy points around 0.7 cpp on average%';

-- [HIGH] transfer_partners: The claim that Marriott transfers are instant from Amex Membership Rewards is an unhedged absolute; Amex-to-Bonvoy transfers are not reliably instant and typically take up to a day or more.
update programs set transfer_partners = replace(transfer_partners::text, 'Instant transfers; no transfer tax (Marriott is a hotel, not a US-domiciled airline so the federal excise tax does not apply).', 'Transfers typically post within 1-2 days; no transfer tax (Marriott is a hotel, not a US-domiciled airline so the federal excise tax does not apply).')::jsonb, last_verified = current_date where slug = 'marriott-bonvoy' and transfer_partners::text like '%Instant transfers; no transfer tax (Marriott is a hotel, not a US-domiciled airline so the federal excise tax does not apply).%';
