-- Auto-generated by scripts/apply-llm-audit.mjs from /tmp/marriott-findings.json
-- Applies HIGH/MEDIUM-severity LLM audit findings as targeted text replacements.
-- Each UPDATE is conditional on the matching string still being present, so
-- re-applying after manual edits is safe (becomes a no-op).
-- ASCII-only per feedback_ascii_only_in_sql_data.md.

-- ============================================================
-- marriott-bonvoy
-- ============================================================

-- [MEDIUM] quirks: This is a forward-looking claim about a policy extending into 2026 that is presented without a specific source date or anchor, making it unverifiable and potentially stale given today is May 2026.
update programs set quirks = replace(quirks, 'Marriott has indicated this policy may continue into the 2026 membership year, but check official Bonvoy communications for confirmation.', 'Marriott indicated in early 2026 that this policy may continue into the 2026 membership year; verify current status on the official Bonvoy communications page before relying on it.'), last_verified = current_date where slug = 'marriott-bonvoy' and quirks like '%Marriott has indicated this policy may continue into the 2026 membership year, but check official Bonvoy communications for confirmation.%';

-- [MEDIUM] transfer_partners: This is an absolute claim about tax treatment that could be inaccurate or change without notice; tax rules are jurisdiction- and structure-specific and should be hedged.
update programs set transfer_partners = replace(transfer_partners::text, 'no transfer tax (Marriott is a hotel, not a US-domiciled airline so the federal excise tax does not apply)', 'no transfer tax currently applies (Marriott is a hotel program, not a US-domiciled airline; confirm current tax treatment before transferring large balances)')::jsonb, last_verified = current_date where slug = 'marriott-bonvoy' and transfer_partners::text like '%no transfer tax (Marriott is a hotel, not a US-domiciled airline so the federal excise tax does not apply)%';

-- [MEDIUM] transfer_partners: Same unhedged absolute claim about no transfer tax appearing in the Chase Ultimate Rewards transfer partner note.
update programs set transfer_partners = replace(transfer_partners::text, 'No transfer tax. Periodic transfer bonuses to Bonvoy run; check the transfer-bonus tracker before moving points.', 'No transfer tax currently applies; confirm current tax treatment before transferring large balances. Periodic transfer bonuses to Bonvoy run; check the transfer-bonus tracker before moving points.')::jsonb, last_verified = current_date where slug = 'marriott-bonvoy' and transfer_partners::text like '%No transfer tax. Periodic transfer bonuses to Bonvoy run; check the transfer-bonus tracker before moving points.%';

-- [MEDIUM] how_to_spend: The specific count of 38 transfer partners is a quickly-drifting factual claim that should be hedged since airline partnerships are added or removed without notice.
update programs set how_to_spend = replace(how_to_spend, '38 frequent-flyer programs at 3:1 ratio for most', '30+ frequent-flyer programs (verify current count on Marriott Bonvoy''s transfer page) at 3:1 ratio for most'), last_verified = current_date where slug = 'marriott-bonvoy' and how_to_spend like '%38 frequent-flyer programs at 3:1 ratio for most%';
