-- Auto-generated by scripts/apply-llm-audit.mjs from /tmp/marriott-findings.json
-- Applies HIGH/MEDIUM-severity LLM audit findings as targeted text replacements.
-- Each UPDATE is conditional on the matching string still being present, so
-- re-applying after manual edits is safe (becomes a no-op).
-- ASCII-only per feedback_ascii_only_in_sql_data.md.

-- ============================================================
-- marriott-bonvoy
-- ============================================================

-- [MEDIUM] intro: "Trade-off" implies dynamic pricing is something Marriott sacrificed scale to get, but dynamic pricing is a consequence of scale/management decisions, not an opposing exchange — the two ideas are related but not in tension.
update programs set intro = replace(intro, 'The trade-off for that scale: Marriott killed the fixed-price award chart back in 2022, so per-night point costs flex with demand within each property''s category.', 'The flip side of that scale: Marriott killed the fixed-price award chart back in 2022, so per-night point costs flex with demand within each property''s category.'), last_verified = current_date where slug = 'marriott-bonvoy' and intro like '%The trade-off for that scale: Marriott killed the fixed-price award chart back in 2022, so per-night point costs flex with demand within each property''s category.%';

-- [MEDIUM] quirks: "Premier Plus Business" is not a clearly identifiable currently-issued card name — the actively-issued Marriott Bonvoy business card from Amex is the "Bonvoy Business Amex"; "Premier Plus Business" appears to be either a legacy Chase product or a mislabeled card, and mixing it into the active-cards section without clarification could mislead readers.
update programs set quirks = replace(quirks, '35K cap - Bonvoy Boundless (Chase, anniversary); Bonvoy basic Amex (renewal); Premier Plus Business (renewal + spend bonus)', '35K cap - Bonvoy Boundless (Chase, anniversary); Bonvoy Business Amex (renewal + spend bonus); Bonvoy basic Amex (renewal)'), last_verified = current_date where slug = 'marriott-bonvoy' and quirks like '%35K cap - Bonvoy Boundless (Chase, anniversary); Bonvoy basic Amex (renewal); Premier Plus Business (renewal + spend bonus)%';

-- [MEDIUM] award_chart: "Premier Plus Business" is not a clearly identifiable currently-issued card name — the actively-issued Marriott Bonvoy business card from Amex is the "Bonvoy Business Amex"; listing an ambiguous or potentially legacy product name in the active-cards table without clarification is misleading.
update programs set award_chart = replace(award_chart, '35,000 pts | Bonvoy Boundless (Chase, anniversary); Bonvoy basic Amex (renewal); Premier Plus Business (renewal + spend bonus)', '35,000 pts | Bonvoy Boundless (Chase, anniversary); Bonvoy Business Amex (renewal + spend bonus); Bonvoy basic Amex (renewal)'), last_verified = current_date where slug = 'marriott-bonvoy' and award_chart like '%35,000 pts | Bonvoy Boundless (Chase, anniversary); Bonvoy basic Amex (renewal); Premier Plus Business (renewal + spend bonus)%';
