-- Auto-generated by scripts/apply-llm-audit.mjs from /tmp/frontier-findings.json
-- Applies HIGH/MEDIUM-severity LLM audit findings as targeted text replacements.
-- Each UPDATE is conditional on the matching string still being present, so
-- re-applying after manual edits is safe (becomes a no-op).
-- ASCII-only per feedback_ascii_only_in_sql_data.md.

-- ============================================================
-- frontier
-- ============================================================

-- [HIGH] intro: Unhedged absolute claim — 'always available' is a guarantee that could change with program terms.
update programs set intro = replace(intro, 'Last Seat is Elite-only and expensive but always available when seats remain.', 'Last Seat is Elite-only and expensive but is available whenever seats remain on the flight, per current program rules.'), last_verified = current_date where slug = 'frontier' and intro like '%Last Seat is Elite-only and expensive but always available when seats remain.%';

-- [HIGH] how_to_spend: Unhedged absolute claim — 'always available' is a guarantee that could change with program terms.
update programs set how_to_spend = replace(how_to_spend, 'Last Seat (Elite-only, most miles, always available when seats remain)', 'Last Seat (Elite-only, most miles, available whenever seats remain per current program rules)'), last_verified = current_date where slug = 'frontier' and how_to_spend like '%Last Seat (Elite-only, most miles, always available when seats remain)%';

-- [MEDIUM] quirks: "Recently" is an unanchored time reference that will become stale without a specific date or year.
update programs set quirks = replace(quirks, '2 free checked bags benefit added recently.', '2 free checked bags benefit (added 2025).'), last_verified = current_date where slug = 'frontier' and quirks like '%2 free checked bags benefit added recently.%';

-- [MEDIUM] quirks: Card annual fees belong on card pages, not program pages.
update programs set quirks = replace(quirks, '$99 annual fee, 5x flyfrontier.com / 3x dining / 1x other.', '5x flyfrontier.com / 3x dining / 1x other.'), last_verified = current_date where slug = 'frontier' and quirks like '%$99 annual fee, 5x flyfrontier.com / 3x dining / 1x other.%';

-- [HIGH] award_chart: Unhedged absolute claim — 'always available' is a guarantee that could change with program terms.
update programs set award_chart = replace(award_chart, 'Always available whenever seats remain.', 'Available whenever seats remain, per current program rules.'), last_verified = current_date where slug = 'frontier' and award_chart like '%Always available whenever seats remain.%';
