-- Auto-generated by scripts/apply-llm-audit.mjs from /tmp/frontier-findings.json
-- Applies HIGH/MEDIUM-severity LLM audit findings as targeted text replacements.
-- Each UPDATE is conditional on the matching string still being present, so
-- re-applying after manual edits is safe (becomes a no-op).
-- ASCII-only per feedback_ascii_only_in_sql_data.md.

-- ============================================================
-- frontier
-- ============================================================

-- [HIGH] intro: Unhedged absolute claim that may not stay true — a new entrant or rebranded carrier could emerge, making 'only national ULCC of size' stale without hedging.
update programs set intro = replace(intro, 'Frontier is the only national ULCC of size still standing', 'Frontier is, as of mid-2026, the only national ULCC of size still operating'), last_verified = current_date where slug = 'frontier' and intro like '%Frontier is the only national ULCC of size still standing%';

-- [MEDIUM] intro: The transition word 'but' implies opposition between 'expensive' and 'available whenever seats remain' — but wide availability and high cost are not opposites; high cost is a consequence or companion of wide availability, not a contrast to it.
update programs set intro = replace(intro, 'Last Seat is Elite-only and expensive but is available whenever seats remain on the flight, per current program rules.', 'Last Seat is Elite-only and expensive, and is available whenever seats remain on the flight, per current program rules.'), last_verified = current_date where slug = 'frontier' and intro like '%Last Seat is Elite-only and expensive but is available whenever seats remain on the flight, per current program rules.%';

-- [MEDIUM] quirks: Sign-up bonus offers change frequently; stating a specific SUB as 'current' without a date anchor will become stale and mislead readers.
update programs set quirks = replace(quirks, 'Current SUB is 50,000 miles after $500 spend in first 90 days.', 'The SUB as of mid-2026 was 50,000 miles after $500 spend in first 90 days - verify current offer before applying.'), last_verified = current_date where slug = 'frontier' and quirks like '%Current SUB is 50,000 miles after $500 spend in first 90 days.%';

-- [MEDIUM] quirks: The early-access pricing window is time-limited and unanchored; readers may see this after the window closes and act on a stale price.
update programs set quirks = replace(quirks, 'GoWild! All-You-Can-Fly Pass** - $349 for the 2026-2027 annual pass during the limited early-access window (regular price $599).', 'GoWild! All-You-Can-Fly Pass - the 2026-2027 annual pass launched at $349 during an early-access window (regular price $599). Confirm current pricing at flyfrontier.com before purchasing.'), last_verified = current_date where slug = 'frontier' and quirks like '%GoWild! All-You-Can-Fly Pass** - $349 for the 2026-2027 annual pass during the limited early-access window (regular price $599).%';

-- [MEDIUM] award_chart: Third-party valuation figures change frequently; citing a specific figure without hedging it as a point-in-time estimate can mislead readers when valuations are updated.
update programs set award_chart = replace(award_chart, 'Average mile value sits around 1.0-1.1 cpp per third-party trackers (TPG mid-2026 valuations)', 'Average mile value sat around 1.0-1.1 cpp per third-party trackers (e.g., TPG mid-2026 valuations); check current estimates before planning a redemption.'), last_verified = current_date where slug = 'frontier' and award_chart like '%Average mile value sits around 1.0-1.1 cpp per third-party trackers (TPG mid-2026 valuations)%';
