-- partner_redemptions backfill: 16 programs (round-5 batch + 6 existing gaps).
-- Each row links a currency program (the one whose miles you would spend) to an
-- operating carrier (the airline you would actually fly), with current point
-- cost ranges, cabin, and key flags.
--
-- Pricing data sourced from each program's published partner award chart
-- where available. Where a program uses dynamic pricing with no published
-- chart, only saver-band ranges are recorded with confidence MEDIUM and
-- notes flagging the dynamic nature.
--
-- Group 1 (round-5): avianca, emirates, etihad, korean-air, aeromexico,
--   virgin-australia, latam, eva-air, air-new-zealand, aegean
-- Group 2 (backfill): delta, united, alaska, hawaiian, southwest, flying-blue

-- =====================================================================
-- AVIANCA LifeMiles (Star Alliance; no YQ on partners; $25 booking fee)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'avianca'), (select id from programs where slug = 'united'),
  'Economy', 'Within North America (single-zone)', 6500, 12500, 'fixed',
  'Single-zone short-haul; no YQ pass-through. Phantom availability common.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'avianca'), (select id from programs where slug = 'united'),
  'Business', 'Within North America short-haul', 15000, 25000, 'fixed',
  'Domestic US business; saver inventory tight on transcon.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'avianca'), (select id from programs where slug = 'miles-and-more'),
  'Business', 'US to Europe via Lufthansa', 63000, 70000, 'fixed',
  'Lufthansa partner award; LH first only released 14 days out to partners.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'avianca'), (select id from programs where slug = 'miles-and-more'),
  'First', 'US to Europe via Lufthansa', 120000, 130000, 'fixed',
  'LH First; saver space sparse. Booking fee $25.',
  'MED', current_date, true, 'none', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'avianca'), (select id from programs where slug = 'ana'),
  'Business', 'US to Asia via ANA', 75000, 85000, 'fixed',
  'ANA partner business; great value vs ANA-direct round-trip rule.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'avianca'), (select id from programs where slug = 'eva-air'),
  'Business', 'US to Asia via EVA Air', 75000, 85000, 'fixed',
  'EVA Royal Laurel; saver opens ~330 days out, narrowbody bias on TPE-SIN.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'avianca'), (select id from programs where slug = 'air-new-zealand'),
  'Business', 'US to Auckland via Air New Zealand', 80000, 90000, 'fixed',
  'NZ business; saver space limited, books online.',
  'MED', current_date, true, 'none', true, 'online', 'north_america', 'south_pacific'),
((select id from programs where slug = 'avianca'), (select id from programs where slug = 'avianca'),
  'Economy', 'Intra-Latin America', 7500, 15000, 'fixed',
  'Own-metal short-haul within Latin America.',
  'HIGH', current_date, true, 'none', true, 'online', 'south_america_1', 'south_america_1'),
((select id from programs where slug = 'avianca'), (select id from programs where slug = 'turkish'),
  'Business', 'US to Europe via Turkish Airlines', 63000, 70000, 'fixed',
  'TK business via IST; some YQ on TK metal but Avianca does not pass it.',
  'MED', current_date, true, 'none', true, 'online', 'north_america', 'europe');

-- =====================================================================
-- EMIRATES Skywards (non-aligned; high YQ own metal; new partner distance chart Mar 4 2026)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'emirates'), (select id from programs where slug = 'emirates'),
  'Business', 'US to Dubai own-metal', 120000, 180000, 'dynamic',
  'Saver bands on own metal; high YQ adds significant cash co-pay.',
  'MED', current_date, true, 'high', true, 'online', 'north_america', 'middle_east'),
((select id from programs where slug = 'emirates'), (select id from programs where slug = 'emirates'),
  'First', 'US to Dubai own-metal', 180000, 300000, 'dynamic',
  'First locked to Silver+ status since May 12 2025; high YQ co-pay.',
  'MED', current_date, true, 'high', true, 'online', 'north_america', 'middle_east'),
((select id from programs where slug = 'emirates'), (select id from programs where slug = 'emirates'),
  'Economy', 'US to Dubai own-metal', 60000, 100000, 'dynamic',
  'Economy saver bands; YQ moderate to high.',
  'MED', current_date, true, 'high', true, 'online', 'north_america', 'middle_east'),
((select id from programs where slug = 'emirates'), (select id from programs where slug = 'jetblue'),
  'Economy', 'US domestic via JetBlue', 3000, 7500, 'fixed',
  'New distance-based partner chart effective Mar 4 2026; short-haul sweet spot.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'emirates'), (select id from programs where slug = 'jetblue'),
  'Economy', 'US transcon via JetBlue', 12500, 20000, 'fixed',
  'Transcon Mint distance band on the new partner chart.',
  'MED', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'emirates'), (select id from programs where slug = 'qantas'),
  'Business', 'US to Australia via Qantas', 110000, 140000, 'fixed',
  'Qantas partner business; YQ moderate. New distance chart applies.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'south_pacific'),
((select id from programs where slug = 'emirates'), (select id from programs where slug = 'jal'),
  'Business', 'US to Asia via JAL', 95000, 130000, 'fixed',
  'JAL partner business; YQ partner-dependent.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'emirates'), (select id from programs where slug = 'korean-air'),
  'Business', 'US to Korea via Korean Air', 95000, 130000, 'fixed',
  'Bilateral partner; verify pricing under post-March 2026 chart.',
  'LOW', current_date, true, 'low', false, 'phone', 'north_america', 'asia_1');

-- =====================================================================
-- ETIHAD Guest (non-aligned; dynamic own; unified 10-band partner distance chart)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'etihad'), (select id from programs where slug = 'etihad'),
  'Business', 'US to Abu Dhabi own-metal', 120000, 200000, 'dynamic',
  'Saver bands on own metal; moderate YQ co-pay.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'middle_east'),
((select id from programs where slug = 'etihad'), (select id from programs where slug = 'etihad'),
  'First', 'US to Abu Dhabi own-metal', 150000, 240000, 'dynamic',
  'A380 First Apartments; dynamic, sparse saver release.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'middle_east'),
((select id from programs where slug = 'etihad'), (select id from programs where slug = 'etihad'),
  'Economy', 'US to Abu Dhabi own-metal', 50000, 100000, 'dynamic',
  'Economy bands; YQ moderate.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'middle_east'),
((select id from programs where slug = 'etihad'), (select id from programs where slug = 'aa'),
  'Economy', 'US domestic via American', 7000, 10000, 'fixed',
  'Legacy partner rate; verify post-AA partnership reset.',
  'LOW', current_date, true, 'low', false, 'phone', 'north_america', 'north_america'),
((select id from programs where slug = 'etihad'), (select id from programs where slug = 'starlux'),
  'Business', 'US to Taipei via Starlux', 90000, 120000, 'fixed',
  'Starlux partner; unified distance chart applies.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'etihad'), (select id from programs where slug = 'garuda-indonesia'),
  'Business', 'Asia to Jakarta via Garuda', 60000, 90000, 'fixed',
  'Garuda partner; phone booking common.',
  'LOW', current_date, true, 'low', false, 'phone', 'asia_1', 'asia_1'),
((select id from programs where slug = 'etihad'), (select id from programs where slug = 'gulf-air'),
  'Business', 'Middle East to Europe via Gulf Air', 50000, 75000, 'fixed',
  'Gulf Air partner; bilateral distance pricing.',
  'LOW', current_date, true, 'low', false, 'phone', 'middle_east', 'europe');

-- =====================================================================
-- KOREAN AIR SkyPass (SkyTeam; published chart with peak/off-peak)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'korean-air'), (select id from programs where slug = 'korean-air'),
  'First', 'JFK to ICN own-metal off-peak', 80000, 80000, 'fixed',
  'Off-peak first; the headline SkyPass sweet spot. Moderate YQ.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'korean-air'), (select id from programs where slug = 'korean-air'),
  'First', 'JFK to ICN own-metal peak', 100000, 125000, 'fixed',
  'Peak first; published chart rate.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'korean-air'), (select id from programs where slug = 'korean-air'),
  'Business', 'JFK to ICN own-metal off-peak', 62500, 62500, 'fixed',
  'Off-peak business; round-trip pricing on chart, halved here for one-way.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'korean-air'), (select id from programs where slug = 'korean-air'),
  'Business', 'JFK to ICN own-metal peak', 75000, 75000, 'fixed',
  'Peak business one-way.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'korean-air'), (select id from programs where slug = 'delta'),
  'Economy', 'US domestic round-trip via Delta', 25000, 25000, 'fixed',
  'Domestic RT economy; published partner chart, no YQ.',
  'HIGH', current_date, true, 'none', false, 'phone', 'north_america', 'north_america'),
((select id from programs where slug = 'korean-air'), (select id from programs where slug = 'delta'),
  'Economy', 'US mainland to Hawaii round-trip via Delta', 25000, 25000, 'fixed',
  'Hawaii RT economy classic SkyPass sweet spot.',
  'HIGH', current_date, true, 'none', false, 'phone', 'north_america', 'north_america'),
((select id from programs where slug = 'korean-air'), (select id from programs where slug = 'klm'),
  'Business', 'US to Europe round-trip via KLM', 80000, 80000, 'fixed',
  'SkyTeam business RT to Europe; partner chart rate.',
  'HIGH', current_date, true, 'low', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'korean-air'), (select id from programs where slug = 'air-france'),
  'Business', 'US to Europe round-trip via Air France', 80000, 80000, 'fixed',
  'AF business RT to Europe; YQ pass-through applies.',
  'HIGH', current_date, true, 'low', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'korean-air'), (select id from programs where slug = 'aeromexico'),
  'Business', 'US to Mexico round-trip via Aeromexico', 50000, 50000, 'fixed',
  'SkyTeam partner; published chart.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'central_america');

-- =====================================================================
-- AEROMEXICO Rewards (SkyTeam; mostly dynamic since Aug 2025)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'aeromexico'), (select id from programs where slug = 'aeromexico'),
  'Economy', 'Mexico domestic own-metal', 5000, 10000, 'fixed',
  'Classic chart rate retained for Mexico domestic short-haul.',
  'HIGH', current_date, true, 'low', true, 'online', 'central_america', 'central_america'),
((select id from programs where slug = 'aeromexico'), (select id from programs where slug = 'aeromexico'),
  'Business', 'US to Mexico City own-metal', 20000, 40000, 'dynamic',
  'Dynamic pricing on cross-border; saver bands at the low end.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'central_america'),
((select id from programs where slug = 'aeromexico'), (select id from programs where slug = 'aeromexico'),
  'Economy', 'US to Mexico City own-metal', 10000, 25000, 'dynamic',
  'Dynamic pricing post-August 2025 reset.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'central_america'),
((select id from programs where slug = 'aeromexico'), (select id from programs where slug = 'delta'),
  'Economy', 'US domestic via Delta', 10000, 25000, 'dynamic',
  'SkyTeam partner; dynamic pricing aligned with Delta SkyMiles.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'aeromexico'), (select id from programs where slug = 'klm'),
  'Business', 'US to Europe one-way via KLM', 80000, 160000, 'dynamic',
  'KLM partner business; dynamic, YQ pass-through.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'aeromexico'), (select id from programs where slug = 'air-france'),
  'Business', 'US to Europe one-way via Air France', 80000, 160000, 'dynamic',
  'AF partner business; dynamic, high YQ pass-through.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'aeromexico'), (select id from programs where slug = 'korean-air'),
  'Business', 'US to Asia via Korean Air', 90000, 180000, 'dynamic',
  'Korean Air SkyTeam partner; phone booking sometimes needed.',
  'LOW', current_date, true, 'low', false, 'mixed', 'north_america', 'asia_1'),
((select id from programs where slug = 'aeromexico'), (select id from programs where slug = 'kenya-airways'),
  'Business', 'Africa intra-region via Kenya Airways', 50000, 90000, 'dynamic',
  'SkyTeam partner; limited award space.',
  'LOW', current_date, true, 'low', false, 'phone', 'sub_saharan_africa', 'sub_saharan_africa');

-- =====================================================================
-- VIRGIN AUSTRALIA Velocity (non-aligned; bilateral chart; SQ-via-Velocity headline)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'virgin-australia'), (select id from programs where slug = 'virgin-australia'),
  'Economy', 'Intra-Australia short-haul (e.g. SYD-MEL)', 7800, 7800, 'fixed',
  'Domestic short-haul saver economy.',
  'HIGH', current_date, true, 'none', true, 'online', 'south_pacific', 'south_pacific'),
((select id from programs where slug = 'virgin-australia'), (select id from programs where slug = 'virgin-australia'),
  'Business', 'Intra-Australia short-haul', 15500, 23500, 'fixed',
  'Domestic business saver to peak.',
  'HIGH', current_date, true, 'none', true, 'online', 'south_pacific', 'south_pacific'),
((select id from programs where slug = 'virgin-australia'), (select id from programs where slug = 'singapore-airlines'),
  'Business', 'US to Singapore via Singapore Airlines', 95000, 135000, 'fixed',
  'KrisFlyer-released saver via Velocity bilateral; phantom space common.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'asia_1'),
((select id from programs where slug = 'virgin-australia'), (select id from programs where slug = 'singapore-airlines'),
  'Business', 'Australia to Singapore via Singapore Airlines', 62000, 90000, 'fixed',
  'AU-SIN business via SQ; bilateral release.',
  'MED', current_date, true, 'low', false, 'phone', 'south_pacific', 'asia_1'),
((select id from programs where slug = 'virgin-australia'), (select id from programs where slug = 'ana'),
  'Business', 'US to Tokyo via ANA', 95000, 135000, 'fixed',
  'ANA partner business; saver bands.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'asia_1'),
((select id from programs where slug = 'virgin-australia'), (select id from programs where slug = 'qatar'),
  'Business', 'US to Doha via Qatar Airways', 113500, 130000, 'fixed',
  'Qsuite via Velocity; high YQ pass-through.',
  'MED', current_date, true, 'high', false, 'phone', 'north_america', 'middle_east'),
((select id from programs where slug = 'virgin-australia'), (select id from programs where slug = 'etihad'),
  'Business', 'Australia to Abu Dhabi via Etihad', 95000, 130000, 'fixed',
  'Etihad partner; bilateral chart.',
  'MED', current_date, true, 'low', false, 'phone', 'south_pacific', 'middle_east'),
((select id from programs where slug = 'virgin-australia'), (select id from programs where slug = 'united'),
  'Business', 'US to Australia via United', 110000, 140000, 'fixed',
  'United partner; bilateral release.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'south_pacific'),
((select id from programs where slug = 'virgin-australia'), (select id from programs where slug = 'air-canada'),
  'Business', 'North America via Air Canada', 75000, 110000, 'fixed',
  'Air Canada partner; saver bands tight.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'north_america'),
((select id from programs where slug = 'virgin-australia'), (select id from programs where slug = 'air-new-zealand'),
  'Business', 'Australia to New Zealand via Air NZ', 40000, 65000, 'fixed',
  'NZ partner; trans-Tasman business.',
  'MED', current_date, true, 'low', false, 'phone', 'south_pacific', 'south_pacific');

-- =====================================================================
-- LATAM Pass (independent for now; partner chart phone-only)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'latam'), (select id from programs where slug = 'latam'),
  'Business', 'US to South America own-metal', 80000, 160000, 'dynamic',
  'Dynamic; saver bands at the low end of the range.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'south_america_1'),
((select id from programs where slug = 'latam'), (select id from programs where slug = 'latam'),
  'Economy', 'US to South America own-metal', 30000, 60000, 'dynamic',
  'Dynamic economy bands.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'south_america_1'),
((select id from programs where slug = 'latam'), (select id from programs where slug = 'latam'),
  'Economy', 'Intra-South America own-metal', 8000, 25000, 'dynamic',
  'Short-haul intra-region.',
  'MED', current_date, true, 'low', true, 'online', 'south_america_1', 'south_america_1'),
((select id from programs where slug = 'latam'), (select id from programs where slug = 'latam'),
  'Business', 'Intra-South America own-metal', 25000, 60000, 'dynamic',
  'Regional business dynamic.',
  'MED', current_date, true, 'low', true, 'online', 'south_america_1', 'south_america_1'),
((select id from programs where slug = 'latam'), (select id from programs where slug = 'delta'),
  'Economy', 'US domestic via Delta', 10000, 25000, 'fixed',
  'Continuing Delta partnership; phone-only booking.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'north_america'),
((select id from programs where slug = 'latam'), (select id from programs where slug = 'delta'),
  'Business', 'US domestic transcon via Delta', 30000, 65000, 'fixed',
  'Delta partner business; phone booking required.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'north_america'),
((select id from programs where slug = 'latam'), (select id from programs where slug = 'aeromexico'),
  'Economy', 'Latin America via Aeromexico', 12000, 30000, 'fixed',
  'Bilateral partnership; opaque chart.',
  'LOW', current_date, true, 'low', false, 'phone', 'south_america_1', 'central_america'),
((select id from programs where slug = 'latam'), (select id from programs where slug = 'qatar'),
  'Business', 'South America to Doha via Qatar', 110000, 160000, 'fixed',
  'Verify pricing post-oneworld rejoin; high YQ on Qatar metal.',
  'LOW', current_date, true, 'high', false, 'phone', 'south_america_1', 'middle_east'),
((select id from programs where slug = 'latam'), (select id from programs where slug = 'iberia'),
  'Business', 'South America to Madrid via Iberia', 90000, 130000, 'fixed',
  'Verify pricing post-oneworld rejoin.',
  'LOW', current_date, true, 'low', false, 'phone', 'south_america_1', 'europe');

-- =====================================================================
-- EVA AIR Infinity MileageLands (Star Alliance; rare published fixed region chart)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'eva-air'), (select id from programs where slug = 'eva-air'),
  'Business', 'Intra-Asia round-trip (TPE-BKK/SIN/HKG)', 50000, 50000, 'fixed',
  'Royal Laurel intra-Asia RT; published chart rate.',
  'HIGH', current_date, true, 'low', true, 'online', 'asia_1', 'asia_1'),
((select id from programs where slug = 'eva-air'), (select id from programs where slug = 'eva-air'),
  'Business', 'US to Asia one-way (LAX/ORD-TPE)', 75000, 80000, 'fixed',
  'Royal Laurel transpacific one-way; published chart.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'eva-air'), (select id from programs where slug = 'eva-air'),
  'Economy', 'US to Asia one-way', 40000, 45000, 'fixed',
  'Economy transpacific one-way.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'eva-air'), (select id from programs where slug = 'ana'),
  'Business', 'US to Tokyo via ANA', 85000, 95000, 'fixed',
  'ANA partner; Star Alliance chart.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'asia_1'),
((select id from programs where slug = 'eva-air'), (select id from programs where slug = 'miles-and-more'),
  'Business', 'US to Europe via Lufthansa', 85000, 95000, 'fixed',
  'LH partner business; less competitive than Aeroplan/Turkish.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'eva-air'), (select id from programs where slug = 'swiss'),
  'Business', 'US to Europe via SWISS', 85000, 95000, 'fixed',
  'SWISS partner; saver release rare.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'eva-air'), (select id from programs where slug = 'united'),
  'Economy', 'US domestic via United', 12500, 25000, 'fixed',
  'UA partner; Star Alliance fixed chart.',
  'HIGH', current_date, true, 'low', false, 'phone', 'north_america', 'north_america'),
((select id from programs where slug = 'eva-air'), (select id from programs where slug = 'air-canada'),
  'Business', 'US to Europe via Air Canada', 85000, 95000, 'fixed',
  'AC partner business; YQ low.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'eva-air'), (select id from programs where slug = 'turkish'),
  'Business', 'US to Europe via Turkish Airlines', 85000, 95000, 'fixed',
  'TK partner business via IST.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'eva-air'), (select id from programs where slug = 'thai'),
  'Business', 'Intra-Asia via Thai Airways', 35000, 50000, 'fixed',
  'Thai partner intra-Asia.',
  'MED', current_date, true, 'low', false, 'phone', 'asia_1', 'asia_1');

-- =====================================================================
-- AIR NEW ZEALAND Airpoints (Star Alliance; APD cashback own metal; distance partners)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'air-new-zealand'), (select id from programs where slug = 'air-new-zealand'),
  'Economy', 'Own-metal cashback (any route)', 50, 1200, 'dynamic',
  'APD model: 1 APD = 1 NZD off cash fare. Range reflects typical APD spend.',
  'HIGH', current_date, true, 'low', true, 'online', 'south_pacific', 'south_pacific'),
((select id from programs where slug = 'air-new-zealand'), (select id from programs where slug = 'air-new-zealand'),
  'Business', 'US to Auckland own-metal cashback', 800, 3000, 'dynamic',
  'Business class APD cashback varies with cash fare.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'south_pacific'),
((select id from programs where slug = 'air-new-zealand'), (select id from programs where slug = 'singapore-airlines'),
  'Business', 'Intra-Asia distance band 1 via SQ', 35000, 45000, 'fixed',
  'SQ partner short distance band.',
  'MED', current_date, true, 'low', false, 'phone', 'asia_1', 'asia_1'),
((select id from programs where slug = 'air-new-zealand'), (select id from programs where slug = 'singapore-airlines'),
  'Business', 'Intra-Asia distance band 2 via SQ (BKK-HKG)', 50000, 65000, 'fixed',
  'SQ partner medium distance band.',
  'MED', current_date, true, 'low', false, 'phone', 'asia_1', 'asia_1'),
((select id from programs where slug = 'air-new-zealand'), (select id from programs where slug = 'ana'),
  'Business', 'US to Tokyo via ANA', 90000, 110000, 'fixed',
  'ANA partner business; distance chart.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'asia_1'),
((select id from programs where slug = 'air-new-zealand'), (select id from programs where slug = 'miles-and-more'),
  'Business', 'US to Europe via Lufthansa', 95000, 115000, 'fixed',
  'LH partner business via distance chart.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'air-new-zealand'), (select id from programs where slug = 'swiss'),
  'Business', 'US to Europe via SWISS', 95000, 115000, 'fixed',
  'SWISS partner business.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'air-new-zealand'), (select id from programs where slug = 'united'),
  'Business', 'US to Europe via United', 80000, 100000, 'fixed',
  'UA partner; lower YQ than European Star carriers.',
  'MED', current_date, true, 'low', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'air-new-zealand'), (select id from programs where slug = 'thai'),
  'Business', 'Intra-Asia via Thai Airways', 40000, 55000, 'fixed',
  'Thai partner intra-Asia.',
  'LOW', current_date, true, 'low', false, 'phone', 'asia_1', 'asia_1');

-- =====================================================================
-- AEGEAN Miles+Bonus (Star Alliance; two charts; phone-only partners; YQ varies)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'aegean'), (select id from programs where slug = 'aegean'),
  'Economy', 'Intra-Europe one-way own-metal', 12000, 15000, 'fixed',
  'Own chart; bookable online.',
  'HIGH', current_date, true, 'low', true, 'online', 'europe', 'europe'),
((select id from programs where slug = 'aegean'), (select id from programs where slug = 'aegean'),
  'Business', 'Intra-Europe one-way own-metal', 22000, 28000, 'fixed',
  'Aegean own-metal business intra-Europe.',
  'HIGH', current_date, true, 'low', true, 'online', 'europe', 'europe'),
((select id from programs where slug = 'aegean'), (select id from programs where slug = 'miles-and-more'),
  'Business', 'US to Europe one-way via Lufthansa', 55000, 55000, 'fixed',
  'LH business via partner chart; high YQ pass-through.',
  'HIGH', current_date, true, 'high', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'aegean'), (select id from programs where slug = 'swiss'),
  'Business', 'US to Europe one-way via SWISS', 55000, 55000, 'fixed',
  'SWISS business; high YQ co-pay.',
  'HIGH', current_date, true, 'high', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'aegean'), (select id from programs where slug = 'austrian'),
  'Business', 'US to Europe one-way via Austrian', 55000, 55000, 'fixed',
  'Austrian business; high YQ co-pay.',
  'MED', current_date, true, 'high', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'aegean'), (select id from programs where slug = 'turkish'),
  'Business', 'US to Europe one-way via Turkish', 45000, 45000, 'fixed',
  'TK business via IST; high YQ pass-through.',
  'HIGH', current_date, true, 'high', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'aegean'), (select id from programs where slug = 'united'),
  'Business', 'US to Europe one-way via United', 55000, 55000, 'fixed',
  'UA business; YQ low (Aegean does not pass UA YQ).',
  'HIGH', current_date, true, 'low', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'aegean'), (select id from programs where slug = 'air-canada'),
  'Business', 'US to Europe one-way via Air Canada', 55000, 55000, 'fixed',
  'AC business; low YQ.',
  'HIGH', current_date, true, 'low', false, 'phone', 'north_america', 'europe'),
((select id from programs where slug = 'aegean'), (select id from programs where slug = 'singapore-airlines'),
  'Business', 'Intra-Asia via Singapore Airlines', 30000, 35000, 'fixed',
  'SQ partner; about 50 EUR cash co-pay typical.',
  'MED', current_date, true, 'low', false, 'phone', 'asia_1', 'asia_1'),
((select id from programs where slug = 'aegean'), (select id from programs where slug = 'ana'),
  'Business', 'US to Tokyo via ANA', 75000, 85000, 'fixed',
  'ANA partner business; ANA does not pass YQ on Aegean awards.',
  'HIGH', current_date, true, 'none', false, 'phone', 'north_america', 'asia_1');

-- =====================================================================
-- DELTA SkyMiles (SkyTeam; dynamic own-metal; partner SkyTeam awards)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'delta'), (select id from programs where slug = 'delta'),
  'Business', 'US to Europe one-way own-metal', 100000, 300000, 'dynamic',
  'Dynamic Delta One; rare flash sales at 60K-75K.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'delta'), (select id from programs where slug = 'delta'),
  'First', 'US domestic own-metal', 25000, 100000, 'dynamic',
  'Dynamic first/Comfort+ pricing.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'delta'), (select id from programs where slug = 'delta'),
  'Economy', 'US domestic own-metal', 5000, 50000, 'dynamic',
  'Dynamic economy; SkyMiles flash sales surface here.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'delta'), (select id from programs where slug = 'delta'),
  'Business', 'US to Asia one-way own-metal', 130000, 350000, 'dynamic',
  'Dynamic transpacific business.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'delta'), (select id from programs where slug = 'virgin-atlantic'),
  'Business', 'US to London via Virgin Atlantic', 50000, 150000, 'dynamic',
  'Most dynamic; rare sweet spots persist via VS bilateral.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'delta'), (select id from programs where slug = 'klm'),
  'Business', 'US to Europe via KLM', 95000, 250000, 'dynamic',
  'KLM SkyTeam partner; YQ pass-through.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'delta'), (select id from programs where slug = 'air-france'),
  'Business', 'US to Europe via Air France', 95000, 250000, 'dynamic',
  'AF SkyTeam partner; high YQ.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'delta'), (select id from programs where slug = 'korean-air'),
  'Business', 'US to Korea via Korean Air', 110000, 220000, 'dynamic',
  'KE SkyTeam partner; saver bookings via online.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'delta'), (select id from programs where slug = 'china-eastern'),
  'Business', 'US to China via China Eastern', 110000, 220000, 'dynamic',
  'MU SkyTeam partner.',
  'LOW', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'delta'), (select id from programs where slug = 'kenya-airways'),
  'Business', 'Africa intra-region via Kenya Airways', 80000, 160000, 'dynamic',
  'KQ SkyTeam partner; phone backup if online fails.',
  'LOW', current_date, true, 'low', false, 'mixed', 'sub_saharan_africa', 'sub_saharan_africa');

-- =====================================================================
-- UNITED MileagePlus (Star Alliance; dynamic own; partner award fixed)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'united'), (select id from programs where slug = 'united'),
  'Business', 'US to Europe one-way own-metal', 60000, 200000, 'dynamic',
  'Dynamic Polaris; saver bands at the low end.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'united'),
  'Economy', 'US domestic own-metal', 5000, 50000, 'dynamic',
  'Dynamic economy. Excursionist Perk grants a complimentary one-way segment on multi-city RT itineraries.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'united'),
  'Business', 'US to Asia one-way own-metal', 80000, 250000, 'dynamic',
  'Dynamic transpacific Polaris.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'miles-and-more'),
  'Business', 'US to Europe via Lufthansa', 80000, 110000, 'fixed',
  'LH Star partner; saver release 14 days out for First.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'swiss'),
  'Business', 'US to Europe via SWISS', 80000, 110000, 'fixed',
  'SWISS Star partner business.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'ana'),
  'Business', 'US to Tokyo via ANA', 80000, 90000, 'fixed',
  'ANA Star partner; great saver release in Round Trip Tickets via partner.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'eva-air'),
  'Business', 'US to Asia via EVA Air', 80000, 90000, 'fixed',
  'EVA Royal Laurel via United partner chart.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'turkish'),
  'Business', 'US to Europe via Turkish Airlines', 80000, 110000, 'fixed',
  'TK Star partner via IST.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'air-canada'),
  'Business', 'US to Europe via Air Canada', 80000, 110000, 'fixed',
  'AC Star partner; saver via United online.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'avianca'),
  'Economy', 'US to Latin America via Avianca', 12500, 25000, 'fixed',
  'Avianca Star partner short-haul Americas.',
  'HIGH', current_date, true, 'low', true, 'online', 'north_america', 'south_america_1'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'copa'),
  'Business', 'US to Latin America via Copa', 35000, 70000, 'fixed',
  'Copa Star partner.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'central_america'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'air-new-zealand'),
  'Business', 'US to Auckland via Air New Zealand', 80000, 100000, 'fixed',
  'NZ Star partner; saver tight.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'south_pacific'),
((select id from programs where slug = 'united'), (select id from programs where slug = 'thai'),
  'Business', 'Intra-Asia via Thai Airways', 35000, 45000, 'fixed',
  'Thai Star partner intra-Asia.',
  'MED', current_date, true, 'low', true, 'online', 'asia_1', 'asia_1');

-- =====================================================================
-- ALASKA Mileage Plan / Atmos Rewards (oneworld + Atmos partners; own metal here)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'alaska'), (select id from programs where slug = 'alaska'),
  'Economy', 'US domestic short-haul own-metal', 5000, 12500, 'dynamic',
  'Dynamic post-Atmos; saver bands at low end.',
  'MED', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'alaska'), (select id from programs where slug = 'alaska'),
  'Business', 'US transcon own-metal', 15000, 25000, 'dynamic',
  'Transcon first dynamic.',
  'MED', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'alaska'), (select id from programs where slug = 'alaska'),
  'Economy', 'US to Hawaii own-metal', 12500, 30000, 'dynamic',
  'Mainland-Hawaii dynamic economy.',
  'MED', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'alaska'), (select id from programs where slug = 'alaska'),
  'Business', 'US to Hawaii own-metal', 30000, 60000, 'dynamic',
  'Mainland-Hawaii first dynamic.',
  'MED', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'alaska'), (select id from programs where slug = 'alaska'),
  'Economy', 'US to Mexico/Canada own-metal', 12500, 25000, 'dynamic',
  'Cross-border short-haul dynamic.',
  'MED', current_date, true, 'none', true, 'online', 'north_america', 'central_america'),
((select id from programs where slug = 'alaska'), (select id from programs where slug = 'hawaiian'),
  'Economy', 'Inter-island Hawaii via Hawaiian', 4500, 4500, 'fixed',
  'Atmos sweet spot inter-island; published rate.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'north_america');

-- Note: Alaska partner awards via JAL/Cathay/Qantas/Finnair/Royal Air Maroc/Fiji/
-- Condor/Hainan/Singapore/Starlux now flow through Atmos Rewards. Cross-reference
-- the atmos program rows for partner-specific pricing.

-- =====================================================================
-- HAWAIIAN HawaiianMiles (deprecated Oct 1 2025; migrating to Atmos)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'hawaiian'), (select id from programs where slug = 'hawaiian'),
  'Economy', 'Inter-island Hawaii one-way own-metal', 4500, 4500, 'fixed',
  'Atmos sweet spot inter-island; published rate.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'hawaiian'), (select id from programs where slug = 'hawaiian'),
  'Economy', 'Mainland to Hawaii own-metal', 15000, 40000, 'dynamic',
  'Dynamic post-merger; saver bands at low end.',
  'MED', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'hawaiian'), (select id from programs where slug = 'hawaiian'),
  'Business', 'Mainland to Hawaii own-metal', 40000, 80000, 'dynamic',
  'Dynamic first-class transpacific.',
  'MED', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'hawaiian'), (select id from programs where slug = 'alaska'),
  'Economy', 'US domestic via Alaska', 12500, 25000, 'dynamic',
  'Codeshare partner via Atmos integration.',
  'MED', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'hawaiian'), (select id from programs where slug = 'jal'),
  'Business', 'US to Asia via JAL', 80000, 130000, 'fixed',
  'Legacy JAL partnership; verify post-Atmos integration.',
  'LOW', current_date, true, 'low', false, 'phone', 'north_america', 'asia_1'),
((select id from programs where slug = 'hawaiian'), (select id from programs where slug = 'korean-air'),
  'Business', 'Hawaii to Korea via Korean Air', 60000, 95000, 'fixed',
  'Limited partnership post Jan 2026; verify availability.',
  'LOW', current_date, true, 'low', false, 'phone', 'north_america', 'asia_1');

-- =====================================================================
-- SOUTHWEST Rapid Rewards (closed ecosystem; only own metal; ~70:1 cpp)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'southwest'), (select id from programs where slug = 'southwest'),
  'Economy', 'US domestic Wanna Get Away own-metal', 5000, 25000, 'dynamic',
  'Revenue-tied at ~1.4 cpp; cheapest fare bucket.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'southwest'), (select id from programs where slug = 'southwest'),
  'Economy', 'US domestic Anytime own-metal', 20000, 50000, 'dynamic',
  'Anytime fare bucket; higher points cost.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'southwest'), (select id from programs where slug = 'southwest'),
  'Economy', 'US to Hawaii own-metal', 25000, 50000, 'dynamic',
  'Mainland-Hawaii revenue-tied.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'southwest'), (select id from programs where slug = 'southwest'),
  'Economy', 'US to Mexico own-metal', 12000, 35000, 'dynamic',
  'Cross-border revenue-tied.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'central_america'),
((select id from programs where slug = 'southwest'), (select id from programs where slug = 'southwest'),
  'Economy', 'US to Caribbean own-metal', 12000, 35000, 'dynamic',
  'Caribbean revenue-tied.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'caribbean'),
((select id from programs where slug = 'southwest'), (select id from programs where slug = 'southwest'),
  'Economy', 'US domestic Business Select own-metal', 30000, 70000, 'dynamic',
  'Business Select fare bucket; priority boarding A1-A15 included.',
  'HIGH', current_date, true, 'none', true, 'online', 'north_america', 'north_america');

-- =====================================================================
-- FLYING BLUE (SkyTeam; dynamic own; Promo Rewards 25-50% off rotational)
-- =====================================================================
insert into partner_redemptions (
  currency_program_id, operating_carrier_id, cabin, region_or_route,
  cost_miles_low, cost_miles_high, pricing_model, notes, confidence,
  last_verified, is_active, fuel_surcharges, bookable_online,
  booking_channel, origin_region, dest_region
) values
((select id from programs where slug = 'flying-blue'), (select id from programs where slug = 'air-france'),
  'Business', 'US to Europe one-way via Air France', 60000, 150000, 'dynamic',
  'AF business dynamic; Promo Rewards can drop pricing 25-50% on rotational routes.',
  'MED', current_date, true, 'high', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'flying-blue'), (select id from programs where slug = 'klm'),
  'Business', 'US to Europe one-way via KLM', 60000, 150000, 'dynamic',
  'KLM business dynamic; Promo Rewards rotational.',
  'MED', current_date, true, 'high', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'flying-blue'), (select id from programs where slug = 'air-france'),
  'First', 'US to Paris one-way via Air France La Premiere', 165000, 300000, 'dynamic',
  'AF La Premiere; status-gated and dynamic. High YQ.',
  'LOW', current_date, true, 'high', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'flying-blue'), (select id from programs where slug = 'air-france'),
  'Economy', 'US to Europe one-way via Air France', 21500, 80000, 'dynamic',
  'Economy dynamic; Promo Rewards lows around 21.5K possible.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'flying-blue'), (select id from programs where slug = 'klm'),
  'Economy', 'US to Europe one-way via KLM', 21500, 80000, 'dynamic',
  'KLM economy dynamic; Promo Rewards eligible.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'flying-blue'), (select id from programs where slug = 'delta'),
  'Economy', 'US domestic via Delta', 10000, 50000, 'dynamic',
  'Delta SkyTeam partner via Flying Blue; dynamic.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'flying-blue'), (select id from programs where slug = 'delta'),
  'Business', 'US transcon via Delta', 30000, 100000, 'dynamic',
  'Delta partner business; dynamic.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'north_america'),
((select id from programs where slug = 'flying-blue'), (select id from programs where slug = 'virgin-atlantic'),
  'Business', 'US to London via Virgin Atlantic', 65000, 160000, 'dynamic',
  'VS partner business; YQ pass-through varies.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'europe'),
((select id from programs where slug = 'flying-blue'), (select id from programs where slug = 'korean-air'),
  'Business', 'US to Asia via Korean Air', 90000, 180000, 'dynamic',
  'KE SkyTeam partner; dynamic.',
  'MED', current_date, true, 'low', true, 'online', 'north_america', 'asia_1'),
((select id from programs where slug = 'flying-blue'), (select id from programs where slug = 'kenya-airways'),
  'Business', 'Africa intra-region via Kenya Airways', 50000, 110000, 'dynamic',
  'KQ SkyTeam partner.',
  'LOW', current_date, true, 'low', false, 'phone', 'sub_saharan_africa', 'sub_saharan_africa'),
((select id from programs where slug = 'flying-blue'), (select id from programs where slug = 'china-eastern'),
  'Business', 'US to China via China Eastern', 90000, 180000, 'dynamic',
  'MU SkyTeam partner; verify saver release.',
  'LOW', current_date, true, 'low', false, 'mixed', 'north_america', 'asia_1');
