-- Add a transient cache of Sonnet-recommended source URLs per field.
--
-- Discovery flow: editor clicks "🔍 Discover source URLs" on the program
-- extract page, providing a starting domain (e.g. united.com). Firecrawl
-- /map returns the site's URL list; Sonnet classifies each URL by which
-- extraction field it best supports (intro / tier_benefits / lounge_access
-- / quirks / etc.). Result is persisted here so the editor can review the
-- suggestions, edit them, then either copy into field_source_urls or hit
-- "Apply suggestions" to bulk-populate.
--
-- Separate from field_source_urls (the editor-confirmed mapping) so we
-- don't mix machine suggestions with curator-approved truth.
--
-- Shape:
--   {
--     "tier_benefits": {
--       "urls": ["https://united.com/.../premier/benefits.html"],
--       "reason": "Page title 'Premier Status Benefits' + tier names in body",
--       "confidence": "high"
--     },
--     "lounge_access": { ... },
--     ...
--     "generated_at": "2026-05-15T...",
--     "starting_url": "https://www.united.com"
--   }

alter table programs
  add column if not exists suggested_field_urls jsonb not null default '{}'::jsonb;

comment on column programs.suggested_field_urls is
  'Sonnet-recommended source URLs per extraction field, generated by the discover-urls action. Editor reviews and either copies into field_source_urls or applies in bulk.';
