-- Backup snapshots metadata table.
--
-- Each row records one snapshot taken either manually from /admin/backups
-- or automatically by the nightly GitHub Action. The actual data dump lives
-- as a JSON file in the Supabase Storage bucket `db-backups`; this table
-- holds the index (when, what label, who, size, storage path).
--
-- Storage bucket setup happens in the same migration so a single apply
-- prepares the whole feature.

create table if not exists backup_snapshots (
  id uuid primary key default gen_random_uuid(),
  taken_at timestamptz not null default now(),
  -- Free-text label: 'manual', 'nightly-cron', 'pre-marriott-cleanup', etc.
  label text not null default 'manual',
  -- Path inside the db-backups storage bucket (e.g. 'snapshots/2026-05-19T12-45-00Z.json.gz')
  storage_path text not null,
  size_bytes bigint not null default 0,
  -- Tables actually included in this snapshot (text array for easy inspection)
  tables_included text[] not null default '{}',
  row_counts jsonb not null default '{}'::jsonb,
  -- Who triggered it: 'admin:<user_id>', 'cron:nightly', 'cli'
  taken_by text,
  -- Free-form notes (e.g. "before bulk re-extraction of all hotels")
  notes text,
  created_at timestamptz not null default now()
);

comment on table backup_snapshots is
  'Index of database snapshots. Actual JSON dumps live in Supabase Storage bucket `db-backups`. Used by /admin/backups and the nightly GitHub Action.';

create index if not exists backup_snapshots_taken_at_idx
  on backup_snapshots (taken_at desc);

create index if not exists backup_snapshots_label_idx
  on backup_snapshots (label);

-- Create the storage bucket if it doesn't exist (idempotent).
-- Bucket is PRIVATE — only the service role can read/write. Editors download
-- via signed URLs generated by the admin page.
insert into storage.buckets (id, name, public)
  values ('db-backups', 'db-backups', false)
  on conflict (id) do nothing;
