/**
 * Country name → ISO 3166-1 alpha-2 code → flag image URL.
 *
 * Used as a fallback when a destination has no editorial imageUrl set.
 * Better than no image at all and helps readers ground unfamiliar
 * destinations geographically.
 *
 * Source: flagcdn.com (free, ISO-keyed PNGs).
 */

const COUNTRY_TO_ISO: Record<string, string> = {
  // North America
  'United States': 'us',
  'Canada':        'ca',
  'Mexico':        'mx',

  // Central America
  'Belize':       'bz',
  'Costa Rica':   'cr',
  'El Salvador':  'sv',
  'Guatemala':    'gt',
  'Honduras':     'hn',
  'Nicaragua':    'ni',
  'Panama':       'pa',

  // Caribbean
  'Anguilla':                  'ai',
  'Antigua and Barbuda':       'ag',
  'Aruba':                     'aw',
  'Bahamas':                   'bs',
  'The Bahamas':               'bs',
  'Barbados':                  'bb',
  'Cayman Islands':            'ky',
  'Cuba':                      'cu',
  'Curaçao':                   'cw',
  'Dominica':                  'dm',
  'Dominican Republic':        'do',
  'Grenada':                   'gd',
  'Guadeloupe':                'gp',
  'Haiti':                     'ht',
  'Jamaica':                   'jm',
  'Martinique':                'mq',
  'Montserrat':                'ms',
  'Puerto Rico':               'pr',
  'Saint Kitts and Nevis':     'kn',
  'Saint Lucia':               'lc',
  'Saint Vincent and the Grenadines': 'vc',
  'Sint Maarten':              'sx',
  'Trinidad and Tobago':       'tt',
  'Turks and Caicos Islands':  'tc',
  'British Virgin Islands':    'vg',

  // South America
  'Argentina': 'ar',
  'Bolivia':   'bo',
  'Brazil':    'br',
  'Chile':     'cl',
  'Colombia':  'co',
  'Ecuador':   'ec',
  'Guyana':    'gy',
  'Paraguay':  'py',
  'Peru':      'pe',
  'Suriname':  'sr',
  'Uruguay':   'uy',
  'Venezuela': 've',

  // Europe
  'Albania':         'al',
  'Andorra':         'ad',
  'Austria':         'at',
  'Belarus':         'by',
  'Belgium':         'be',
  'Bosnia and Herzegovina': 'ba',
  'Bulgaria':        'bg',
  'Croatia':         'hr',
  'Cyprus':          'cy',
  'Czech Republic':  'cz',
  'Czechia':         'cz',
  'Denmark':         'dk',
  'Estonia':         'ee',
  'Finland':         'fi',
  'France':          'fr',
  'Germany':         'de',
  'Greece':          'gr',
  'Hungary':         'hu',
  'Iceland':         'is',
  'Ireland':         'ie',
  'Italy':           'it',
  'Kosovo':          'xk',
  'Latvia':          'lv',
  'Liechtenstein':   'li',
  'Lithuania':       'lt',
  'Luxembourg':      'lu',
  'Malta':           'mt',
  'Moldova':         'md',
  'Monaco':          'mc',
  'Montenegro':      'me',
  'Netherlands':     'nl',
  'North Macedonia': 'mk',
  'Norway':          'no',
  'Poland':          'pl',
  'Portugal':        'pt',
  'Romania':         'ro',
  'Russia':          'ru',
  'San Marino':      'sm',
  'Serbia':          'rs',
  'Slovakia':        'sk',
  'Slovenia':        'si',
  'Spain':           'es',
  'Sweden':          'se',
  'Switzerland':     'ch',
  'Türkiye':         'tr',
  'Turkey':          'tr',
  'Ukraine':         'ua',
  'United Kingdom':  'gb',
  'Vatican City':    'va',

  // Africa
  'Algeria':       'dz',
  'Angola':        'ao',
  'Benin':         'bj',
  'Botswana':      'bw',
  'Burkina Faso':  'bf',
  'Burundi':       'bi',
  'Cabo Verde':    'cv',
  'Cape Verde':    'cv',
  'Cameroon':      'cm',
  'Central African Republic': 'cf',
  'Chad':          'td',
  'Comoros':       'km',
  'Congo':         'cg',
  'Democratic Republic of the Congo': 'cd',
  'Djibouti':      'dj',
  'Egypt':         'eg',
  'Equatorial Guinea': 'gq',
  'Eritrea':       'er',
  'Eswatini':      'sz',
  'Ethiopia':      'et',
  'Gabon':         'ga',
  'Gambia':        'gm',
  'Ghana':         'gh',
  'Guinea':        'gn',
  'Guinea-Bissau': 'gw',
  'Ivory Coast':   'ci',
  "Côte d'Ivoire": 'ci',
  'Kenya':         'ke',
  'Lesotho':       'ls',
  'Liberia':       'lr',
  'Libya':         'ly',
  'Madagascar':    'mg',
  'Malawi':        'mw',
  'Mali':          'ml',
  'Mauritania':    'mr',
  'Mauritius':     'mu',
  'Morocco':       'ma',
  'Mozambique':    'mz',
  'Namibia':       'na',
  'Niger':         'ne',
  'Nigeria':       'ng',
  'Rwanda':        'rw',
  'Senegal':       'sn',
  'Seychelles':    'sc',
  'Sierra Leone':  'sl',
  'Somalia':       'so',
  'South Africa':  'za',
  'South Sudan':   'ss',
  'Sudan':         'sd',
  'Tanzania':      'tz',
  'Togo':          'tg',
  'Tunisia':       'tn',
  'Uganda':        'ug',
  'Zambia':        'zm',
  'Zimbabwe':      'zw',

  // Middle East
  'Bahrain':       'bh',
  'Iran':          'ir',
  'Iraq':          'iq',
  'Israel':        'il',
  'Jordan':        'jo',
  'Kuwait':        'kw',
  'Lebanon':       'lb',
  'Oman':          'om',
  'Palestine':     'ps',
  'Qatar':         'qa',
  'Saudi Arabia':  'sa',
  'Syria':         'sy',
  'United Arab Emirates': 'ae',
  'Yemen':         'ye',

  // Asia
  'Afghanistan':   'af',
  'Armenia':       'am',
  'Azerbaijan':    'az',
  'Bangladesh':    'bd',
  'Bhutan':        'bt',
  'Brunei':        'bn',
  'Cambodia':      'kh',
  'China':         'cn',
  'Georgia':       'ge',
  'Hong Kong':     'hk',
  'India':         'in',
  'Indonesia':     'id',
  'Japan':         'jp',
  'Kazakhstan':    'kz',
  'North Korea':   'kp',
  'South Korea':   'kr',
  'Kyrgyzstan':    'kg',
  'Laos':          'la',
  'Macao':         'mo',
  'Malaysia':      'my',
  'Maldives':      'mv',
  'Mongolia':      'mn',
  'Myanmar':       'mm',
  'Nepal':         'np',
  'Pakistan':      'pk',
  'Philippines':   'ph',
  'Singapore':     'sg',
  'Sri Lanka':     'lk',
  'Taiwan':        'tw',
  'Tajikistan':    'tj',
  'Thailand':      'th',
  'Timor-Leste':   'tl',
  'Turkmenistan':  'tm',
  'Uzbekistan':    'uz',
  'Vietnam':       'vn',

  // Oceania
  'Australia':         'au',
  'Fiji':              'fj',
  'French Polynesia':  'pf',
  'Guam':              'gu',
  'Kiribati':          'ki',
  'Marshall Islands':  'mh',
  'Micronesia':        'fm',
  'Nauru':             'nr',
  'New Caledonia':     'nc',
  'New Zealand':       'nz',
  'Palau':             'pw',
  'Papua New Guinea':  'pg',
  'Samoa':             'ws',
  'Solomon Islands':   'sb',
  'Tonga':             'to',
  'Tuvalu':            'tv',
  'Vanuatu':           'vu',
}

export function flagUrlForCountry(
  country: string | null | undefined,
  size: 'w160' | 'w320' | 'w640' | 'w1280' = 'w1280'
): string | null {
  if (!country) return null
  const iso = COUNTRY_TO_ISO[country.trim()]
  if (!iso) return null
  return `https://flagcdn.com/${size}/${iso}.png`
}
